'use strict';

/* ══════════════════════════════════════════════════════════
   LOCH — Hole-Em-All-style drag-physics puzzle ("Loch")

   Unlike Water Sort / Parkplatz / Mosaik (tap-based, discrete-move
   puzzles), this is a continuous pointer-drag toy: the player drags a
   growing black hole around a board, and any object it passes over gets
   swallowed once the hole has grown big enough for it — exactly the "Hole
   Em All" mobile-game mechanic. A level is a fixed, pre-verified set of
   objects (see scripts/generate-hole-levels.js); it's cleared once every
   object on the board has been swallowed.

   Sizing rule: every object has an integer tier (index into HL_TIERS,
   1-based); the hole has a continuous `size` stat and can swallow any
   object with tier <= size. Swallowing an object of tier T sets
   size = max(size, T + 1) — monotonic growth, so a level is solvable
   exactly when a smallest-first playthrough clears it (verified offline
   by the generator, not re-checked at runtime).

   Unlike the other three minigames' "pay to unlock extra capacity" relief
   valve, here the paid action gates the whole level: a freshly reached
   level starts LOCKED (an overlay covers the board) and requires one
   correct quiz answer via the shared askQuestions() to unlock dragging —
   see hlStartAttempt(). Once unlocked, replaying the SAME level via the
   restart button is free, exactly like Water Sort's/Parkplatz's/Mosaik's
   restart buttons — only reaching a NEW level re-locks and re-charges.

   Because the hole moves continuously, this needs a real
   requestAnimationFrame loop (hlTick), same as Mosaik's belt — unlike
   every other screen's rebuild-on-tap model. Rendering is a single
   canvas (no separate overlay/particle layers — object count per level is
   small, so redrawing everything each frame is cheap).
══════════════════════════════════════════════════════════ */

const HL_TIERS = ['📌', '🔘', '🪙', '🍎', '☕', '📕', '👟', '⚽', '🪑', '🚲', '🚗', '🌳', '🏠', '🐋'];

// Generated by scripts/generate-hole-levels.js — each entry is one level's
// object layout: s = hole's starting size, o = objects as
// [tier, xPermille, yPermille] (position normalized 0..1000 across the
// board). Every level is pre-verified solvable by a smallest-first
// playthrough — see the generator's verifySolvable().
const HL_LEVELS = [{"s":1,"o":[[1,514,455],[2,809,845],[1,216,733],[3,186,97]]},{"s":1,"o":[[1,615,188],[2,716,404],[3,366,99],[3,865,511]]},{"s":1,"o":[[1,488,149],[2,262,430],[2,218,239],[1,126,743]]},{"s":1,"o":[[1,471,181],[1,135,176],[1,890,141],[2,853,928]]},{"s":1,"o":[[1,213,817],[1,330,910],[1,118,570],[2,396,402],[1,764,380]]},{"s":1,"o":[[1,800,742],[2,299,375],[1,589,652],[2,179,709],[3,634,216]]},{"s":1,"o":[[1,90,370],[1,669,865],[2,587,655],[3,507,387],[3,810,735]]},{"s":1,"o":[[1,325,886],[1,291,215],[2,486,796],[3,676,96],[2,915,583]]},{"s":1,"o":[[1,90,867],[1,644,386],[2,89,687],[2,824,563],[1,240,151]]},{"s":1,"o":[[1,611,455],[1,918,439],[1,310,876],[1,841,228],[1,426,528]]},{"s":1,"o":[[1,633,715],[1,808,294],[2,712,510],[1,269,142],[1,232,774],[2,465,677]]},{"s":1,"o":[[1,547,547],[1,809,189],[1,443,895],[2,195,680],[3,189,188],[2,418,284]]},{"s":1,"o":[[1,760,139],[2,320,876],[1,517,301],[3,819,309],[4,508,812],[1,346,201]]},{"s":1,"o":[[1,114,66],[2,388,155],[1,536,863],[3,159,844],[3,726,425],[1,538,679]]},{"s":1,"o":[[1,639,408],[1,655,81],[2,410,751],[2,375,422],[2,923,131],[2,562,915]]},{"s":1,"o":[[1,266,417],[2,882,591],[2,536,615],[2,567,318],[2,76,885],[2,230,672]]},{"s":1,"o":[[1,438,808],[1,234,107],[1,886,406],[2,429,255],[2,890,784],[1,128,485]]},{"s":1,"o":[[1,635,533],[1,722,796],[2,366,725],[3,796,127],[1,816,654],[1,279,118],[4,480,158]]},{"s":1,"o":[[1,769,841],[2,174,89],[2,824,390],[2,327,841],[3,646,101],[1,469,915],[3,275,252]]},{"s":1,"o":[[1,885,309],[1,111,752],[1,476,393],[2,112,502],[2,229,180],[3,678,241],[1,932,98]]},{"s":1,"o":[[1,557,406],[2,859,147],[3,336,298],[1,270,594],[4,672,796],[5,766,405],[4,356,905]]},{"s":1,"o":[[1,100,445],[1,825,688],[1,372,787],[2,387,399],[3,811,193],[2,582,490],[3,132,717]]},{"s":1,"o":[[1,564,412],[1,296,310],[1,700,284],[2,746,621],[1,597,778],[3,118,527],[3,101,121]]},{"s":1,"o":[[1,826,309],[1,405,718],[1,173,774],[2,518,832],[2,683,186],[2,539,342],[3,794,833],[3,272,89]]},{"s":1,"o":[[1,232,711],[1,404,111],[2,257,361],[3,787,131],[2,620,311],[1,334,846],[1,690,759],[3,201,163]]},{"s":1,"o":[[1,752,828],[1,345,206],[1,423,79],[2,447,342],[1,696,132],[3,85,260],[1,538,781],[1,735,620]]},{"s":1,"o":[[1,735,775],[2,495,557],[2,232,556],[3,286,235],[3,885,864],[1,796,75],[2,537,738],[4,791,518]]},{"s":1,"o":[[1,114,294],[1,222,83],[2,819,140],[3,543,844],[1,471,119],[4,560,278],[5,222,481],[2,671,682]]},{"s":1,"o":[[1,762,754],[1,575,814],[2,329,218],[2,158,551],[1,389,761],[1,388,540],[3,662,480],[2,119,812]]},{"s":1,"o":[[1,303,63],[2,615,104],[3,851,501],[1,570,378],[4,154,707],[5,171,383],[3,435,530],[2,397,916]]},{"s":1,"o":[[1,580,935],[2,475,98],[2,114,268],[1,801,88],[3,504,650],[4,691,508],[2,281,241],[2,238,737],[4,513,339]]},{"s":1,"o":[[1,522,867],[1,143,478],[1,307,164],[2,834,402],[2,700,224],[2,78,184],[2,355,743],[1,195,794],[2,798,86]]},{"s":1,"o":[[1,311,180],[1,749,660],[1,562,409],[2,113,729],[1,543,610],[1,275,613],[1,127,507],[2,745,847],[2,684,177]]},{"s":1,"o":[[1,244,605],[1,740,435],[2,392,690],[3,548,819],[2,400,454],[2,157,176],[3,412,176],[3,753,737],[2,600,534]]},{"s":1,"o":[[1,487,61],[1,804,816],[1,225,428],[1,309,181],[1,283,825],[2,681,87],[2,854,291],[3,369,681],[1,924,483]]},{"s":1,"o":[[1,398,598],[2,333,779],[3,775,260],[2,856,832],[3,163,232],[2,891,457],[3,287,91],[3,281,473],[1,191,707]]},{"s":1,"o":[[1,448,280],[2,414,432],[3,654,550],[1,830,170],[3,494,697],[4,660,352],[1,110,682],[1,314,930],[3,232,124]]},{"s":1,"o":[[1,222,686],[1,672,713],[2,887,875],[1,583,899],[1,360,232],[3,499,636],[4,822,369],[4,140,218],[2,587,145],[5,121,847]]},{"s":1,"o":[[1,731,276],[2,265,353],[1,570,69],[1,307,737],[3,764,907],[2,356,501],[4,135,877],[3,845,508],[3,385,133],[3,846,130]]},{"s":1,"o":[[1,72,720],[1,398,391],[1,133,858],[1,579,606],[1,340,234],[1,227,507],[2,770,316],[1,682,886],[2,910,115],[1,132,133]]},{"s":1,"o":[[1,863,223],[1,637,624],[2,451,398],[2,849,550],[3,660,394],[3,152,807],[3,540,241],[2,865,856],[2,275,92],[3,194,435]]},{"s":1,"o":[[1,467,145],[1,616,420],[1,386,309],[2,648,902],[3,556,712],[3,294,874],[1,284,580],[4,866,826],[5,126,178],[3,810,413]]},{"s":1,"o":[[1,856,525],[2,913,878],[3,598,128],[1,445,305],[2,137,808],[1,796,307],[2,175,425],[3,692,680],[1,618,327],[2,779,149]]},{"s":1,"o":[[1,291,211],[2,228,797],[1,805,362],[3,125,615],[1,631,572],[4,537,146],[4,780,885],[3,413,470],[2,884,720],[1,918,554],[2,926,160]]},{"s":1,"o":[[1,847,457],[2,527,184],[1,352,83],[1,346,412],[2,568,688],[2,465,552],[2,906,139],[3,239,884],[2,724,197],[2,271,561],[1,147,269]]},{"s":1,"o":[[1,350,82],[2,807,918],[2,506,907],[2,349,333],[1,840,85],[3,700,419],[4,425,720],[2,176,500],[4,131,286],[5,847,643],[5,131,694]]},{"s":1,"o":[[1,463,649],[2,114,407],[2,887,423],[2,720,909],[3,494,817],[2,624,541],[1,282,124],[3,410,479],[1,138,184],[1,801,160],[4,839,674]]},{"s":1,"o":[[1,133,648],[1,452,916],[1,670,347],[1,205,231],[1,306,96],[2,772,761],[3,356,325],[3,825,563],[2,565,665],[3,855,133],[1,163,856]]},{"s":1,"o":[[1,111,579],[1,528,524],[1,418,126],[1,784,802],[1,122,195],[2,863,259],[1,416,691],[2,608,725],[2,741,540],[3,166,917],[1,235,706]]},{"s":1,"o":[[1,596,149],[2,182,405],[3,600,454],[3,891,633],[3,251,230],[2,451,912],[3,707,678],[4,392,426],[3,837,189],[4,814,426],[4,268,790]]},{"s":1,"o":[[1,773,768],[2,586,494],[1,668,336],[3,212,349],[4,169,658],[3,205,864],[5,871,517],[6,497,857],[5,570,174],[4,369,573],[6,870,260],[4,139,160]]},{"s":1,"o":[[1,419,149],[2,610,251],[1,378,811],[2,887,200],[3,512,420],[4,561,760],[2,762,572],[3,130,783],[4,172,564],[4,812,771],[2,169,250],[3,369,609]]},{"s":1,"o":[[1,869,706],[2,185,700],[1,705,493],[1,701,916],[2,144,165],[2,560,680],[3,566,251],[2,201,907],[3,221,461],[3,823,345],[4,356,234],[2,430,793]]},{"s":1,"o":[[1,543,630],[1,894,796],[2,735,668],[3,362,354],[1,474,877],[2,545,327],[3,262,101],[3,118,649],[1,116,848],[3,120,238],[2,819,224],[3,667,873]]},{"s":1,"o":[[1,571,587],[2,569,233],[3,268,121],[3,338,594],[3,730,464],[1,846,672],[4,825,274],[5,737,836],[6,218,859],[5,114,512],[6,468,812],[7,369,348]]},{"s":1,"o":[[1,245,371],[2,774,147],[3,508,881],[3,754,582],[2,782,847],[2,595,76],[3,510,636],[3,326,183],[1,670,259],[3,910,427],[1,252,913],[4,269,724]]},{"s":1,"o":[[1,641,323],[2,223,597],[3,396,382],[3,791,533],[4,434,862],[1,473,669],[2,843,172],[1,535,479],[4,100,393],[5,125,850],[2,210,164],[5,798,875],[5,517,138]]},{"s":1,"o":[[1,748,329],[2,350,412],[1,809,673],[2,477,196],[1,531,602],[1,815,919],[3,785,98],[1,95,896],[3,324,673],[3,95,222],[4,566,405],[4,393,893],[1,937,754]]},{"s":1,"o":[[1,816,759],[1,872,339],[2,329,631],[2,457,348],[2,662,406],[1,618,853],[1,179,780],[1,105,390],[1,618,623],[1,370,851],[3,300,218],[1,569,176],[2,727,167]]},{"s":1,"o":[[1,74,854],[1,699,461],[1,847,394],[2,818,856],[2,924,105],[1,336,657],[2,837,576],[1,531,825],[2,464,462],[2,233,250],[1,191,671],[1,412,910],[3,396,170]]}];
const HL_LEVEL_COUNT = HL_LEVELS.length;

function hlGenerateLevel(levelIndex) {
  const lvl = HL_LEVELS[levelIndex];
  return {
    startSize: lvl.s,
    objects: lvl.o.map(([tier, x, y]) => ({ tier, x: x / 1000, y: y / 1000 })),
  };
}

function hlRadiusForSize(size, w, h) {
  return (0.05 + size * 0.011) * Math.min(w, h);
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.hole
══════════════════════════════════════════════════════════ */
let hlRafId = null;
let hlLastFrameTime = null;
let hlClearing = false;           // true once the current level's clear sequence has fired, so it doesn't refire every frame during the advance delay
let hlAnims = [];                 // in-flight swallow animations: { i, tier, x0, y0, t0, duration } (canvas-pixel coords)
let hlHoleX = 0, hlHoleY = 0;     // live hole position, canvas-pixel space — not persisted, recentred on every level (re)start
let hlDragTargetX = 0, hlDragTargetY = 0;
let hlVisualSize = 1;             // eased toward G.hole.size each frame, purely cosmetic (eating rules use the real size)
let hlDragging = false;

function hlSetupCanvas() {
  const canvas = document.getElementById("hl-board");
  if (!canvas) return;
  const rect = canvas.getBoundingClientRect();
  canvas.width = Math.max(1, Math.round(rect.width));
  canvas.height = Math.max(1, Math.round(rect.height));
  hlHoleX = hlDragTargetX = canvas.width / 2;
  hlHoleY = hlDragTargetY = canvas.height / 2;
  hlVisualSize = G.hole.size;
  hlBindPointerEvents();
}

function hlBindPointerEvents() {
  const canvas = document.getElementById("hl-board");
  if (!canvas || canvas.dataset.hlBound) return;
  canvas.dataset.hlBound = "1";
  const posFromEvent = e => {
    const rect = canvas.getBoundingClientRect();
    return {
      x: Math.min(Math.max(e.clientX - rect.left, 0), rect.width),
      y: Math.min(Math.max(e.clientY - rect.top, 0), rect.height),
    };
  };
  canvas.addEventListener("pointerdown", e => {
    if (!G.hole.unlocked) return;
    hlDragging = true;
    canvas.setPointerCapture(e.pointerId);
    const p = posFromEvent(e);
    hlDragTargetX = p.x; hlDragTargetY = p.y;
  });
  canvas.addEventListener("pointermove", e => {
    if (!hlDragging) return;
    const p = posFromEvent(e);
    hlDragTargetX = p.x; hlDragTargetY = p.y;
  });
  const endDrag = () => { hlDragging = false; };
  canvas.addEventListener("pointerup", endDrag);
  canvas.addEventListener("pointercancel", endDrag);
}

function hlRenderInfo(level) {
  const hl = G.hole;
  const infoEl = document.getElementById("hl-level-info");
  if (infoEl) infoEl.textContent = `Level ${hl.currentLevelIndex + 1} / ${HL_LEVEL_COUNT}`;
  const overlay = document.getElementById("hl-start-overlay");
  if (overlay) overlay.hidden = !!hl.unlocked;
}

function hlStartLevel(levelIndex) {
  const hl = G.hole;
  const level = hlGenerateLevel(levelIndex);
  hl.currentLevelIndex = levelIndex;
  hl.unlocked = false;
  hl.size = level.startSize;
  hl.swallowedMask = new Array(level.objects.length).fill(false);
  hlAnims = [];
  hlClearing = false;
  hlDragging = false;
  hlSetupCanvas();
  hlRenderInfo(level);
  saveState();
}

// Same role as msEnsureQueueAndLevel/plEnsureQueueAndLevel/wsEnsureQueueAndLevel:
// rebuilds the shuffled play queue if it's empty or references levels that
// no longer exist (the pool was regenerated at a different size), restores
// in-progress state otherwise, and (re)starts the render loop.
function hlEnsureQueueAndLevel() {
  const hl = G.hole;
  const staleIndex = hl.playOrder.some(i => i >= HL_LEVEL_COUNT) ||
    (hl.currentLevelIndex != null && hl.currentLevelIndex >= HL_LEVEL_COUNT);
  if (!hl.playOrder.length || staleIndex) {
    hl.playOrder = shuffleArray([...Array(HL_LEVEL_COUNT).keys()]);
    hl.playOrderPos = 0;
    hl.currentLevelIndex = null;
  }
  if (hl.currentLevelIndex == null || !hl.swallowedMask.length) {
    hlStartLevel(hl.playOrder[hl.playOrderPos]);
  } else {
    hlClearing = false;
    hlSetupCanvas();
    hlRenderInfo(hlGenerateLevel(hl.currentLevelIndex));
  }
  hlStartLoop();
}

// The paid gate: mirrors wsBuyExtraBottle/plBuyExtraBay/msBuyExtraSlot
// exactly (hasActiveQuestions check + toast, then askQuestions for 1),
// except here it unlocks the whole level rather than one extra capacity
// unit — reaching a level you haven't paid for yet is what "costs a
// question" in this game.
function hlStartAttempt() {
  const hl = G.hole;
  if (hl.currentLevelIndex == null || hl.unlocked) return;
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🕳️ Level starten", 1, () => {
    hl.unlocked = true;
    saveState();
    hlRenderInfo(hlGenerateLevel(hl.currentLevelIndex));
  }, null);
}

// Free, like every other minigame's restart: resets progress on the
// CURRENT level only (same fixed layout) without re-locking it, since
// it isn't a new level — just retrying one already paid for.
function hlRestartLevel() {
  const hl = G.hole;
  if (hl.currentLevelIndex == null) return;
  const level = hlGenerateLevel(hl.currentLevelIndex);
  hl.size = level.startSize;
  hl.swallowedMask = new Array(level.objects.length).fill(false);
  hlAnims = [];
  hlClearing = false;
  hlSetupCanvas();
  hlRenderInfo(level);
  saveState();
  showToast("🔄 Level neu gestartet.");
}

function hlOnLevelCleared() {
  showToast("🕳️ Level geschafft!");
  saveState();
  setTimeout(hlAdvanceToNextLevel, 900);
}

function hlAdvanceToNextLevel() {
  const hl = G.hole;
  hl.playOrderPos++;
  if (hl.playOrderPos >= hl.playOrder.length) {
    const prevLast = hl.playOrder[hl.playOrder.length - 1];
    const order = shuffleArray([...Array(HL_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    hl.playOrder = order;
    hl.playOrderPos = 0;
  }
  hlStartLevel(hl.playOrder[hl.playOrderPos]);
}

/* ══════════════════════════════════════════════════════════
   TICK / RENDER — single canvas, redrawn whole every frame (object counts
   are small, so no incremental-redraw trick like Mosaik's picture buffer
   is needed).
══════════════════════════════════════════════════════════ */
function hlCheckSwallows(level) {
  const hl = G.hole;
  if (hlClearing) return;
  const canvas = document.getElementById("hl-board");
  if (!canvas) return;
  const w = canvas.width, h = canvas.height;
  const radiusPx = hlRadiusForSize(hlVisualSize, w, h);
  let anySwallowed = false;
  level.objects.forEach((obj, i) => {
    if (hl.swallowedMask[i] || hlAnims.some(a => a.i === i)) return;
    if (obj.tier > hl.size) return; // too big — resists for now
    const ox = obj.x * w, oy = obj.y * h;
    if (Math.hypot(ox - hlHoleX, oy - hlHoleY) > radiusPx) return;
    hl.swallowedMask[i] = true;
    hl.size = Math.max(hl.size, obj.tier + 1);
    hlAnims.push({ i, tier: obj.tier, x0: ox, y0: oy, t0: performance.now(), duration: 260 });
    anySwallowed = true;
  });
  if (anySwallowed) saveState();
  if (hl.swallowedMask.every(Boolean)) { hlClearing = true; hlOnLevelCleared(); }
}

function hlDrawFrame(level) {
  const canvas = document.getElementById("hl-board");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");
  const w = canvas.width, h = canvas.height;
  const hl = G.hole;

  const bg = ctx.createLinearGradient(0, 0, 0, h);
  bg.addColorStop(0, "#2e3c36");
  bg.addColorStop(1, "#1b2620");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, w, h);

  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  level.objects.forEach((obj, i) => {
    if (hl.swallowedMask[i] || hlAnims.some(a => a.i === i)) return;
    ctx.font = `${14 + obj.tier * 5}px sans-serif`;
    ctx.fillText(HL_TIERS[obj.tier - 1], obj.x * w, obj.y * h);
  });

  const now = performance.now();
  for (let k = hlAnims.length - 1; k >= 0; k--) {
    const a = hlAnims[k];
    const t = Math.min(1, (now - a.t0) / a.duration);
    const ex = a.x0 + (hlHoleX - a.x0) * t;
    const ey = a.y0 + (hlHoleY - a.y0) * t;
    const fontPx = (14 + a.tier * 5) * (1 - t);
    if (fontPx > 0.5) {
      ctx.font = `${fontPx}px sans-serif`;
      ctx.globalAlpha = 1 - t;
      ctx.fillText(HL_TIERS[a.tier - 1], ex, ey);
      ctx.globalAlpha = 1;
    }
    if (t >= 1) hlAnims.splice(k, 1);
  }

  if (hl.unlocked) {
    const radius = hlRadiusForSize(hlVisualSize, w, h);
    const grad = ctx.createRadialGradient(hlHoleX, hlHoleY, 0, hlHoleX, hlHoleY, radius);
    grad.addColorStop(0, "#000000");
    grad.addColorStop(0.75, "#120a1e");
    grad.addColorStop(1, "rgba(150,110,255,0.35)");
    ctx.fillStyle = grad;
    ctx.beginPath();
    ctx.arc(hlHoleX, hlHoleY, radius, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "rgba(180,140,255,0.6)";
    ctx.lineWidth = 2;
    ctx.stroke();
  }
}

function hlStartLoop() {
  if (hlRafId != null) return;
  const frame = t => {
    const screenEl = document.getElementById("screen-hole");
    if (!screenEl || screenEl.hidden) { hlRafId = null; hlLastFrameTime = null; return; } // tab switched away — stop, restarted by hlEnsureQueueAndLevel on return
    const hl = G.hole;
    if (hl.currentLevelIndex == null) { hlRafId = requestAnimationFrame(frame); return; }
    const level = hlGenerateLevel(hl.currentLevelIndex);
    const dtMs = hlLastFrameTime == null ? 0 : Math.min(200, t - hlLastFrameTime); // clamp huge gaps (tab was backgrounded)
    hlLastFrameTime = t;

    if (hl.unlocked) {
      const ease = 1 - Math.pow(0.001, dtMs / 1000); // frame-rate-independent "weighty follow" easing
      hlHoleX += (hlDragTargetX - hlHoleX) * ease;
      hlHoleY += (hlDragTargetY - hlHoleY) * ease;
      hlVisualSize += (hl.size - hlVisualSize) * Math.min(1, dtMs / 250);
      hlCheckSwallows(level);
    }
    hlDrawFrame(level);
    hlRafId = requestAnimationFrame(frame);
  };
  hlRafId = requestAnimationFrame(frame);
}

window.hlEnsureQueueAndLevel = hlEnsureQueueAndLevel;
window.hlStartAttempt = hlStartAttempt;
window.hlRestartLevel = hlRestartLevel;
