'use strict';

/* ══════════════════════════════════════════════════════════
   MOSAIK — pixel-art dissolve puzzle (classic SameGame)

   A grid of colored pixels. Tapping a pixel selects its whole orthogonally-
   connected same-color group; if that group has ≥2 cells, the group is
   removed ("placing a container that sucks up reachable same-colored
   pixels"). Tapping an isolated (group size 1) pixel does nothing — this
   is deliberate: if singletons were removable, every board would trivially
   clear in exactly cellCount taps regardless of layout, which would gut
   the game's actual difficulty signal.

   Gravity, assumed classic SameGame two-phase (not explicitly confirmed
   beyond "pixels fall/shift" in general — a one-line rendering change if
   wrong, not a solver redesign): remaining cells in a column fall down to
   close vertical gaps; if a column becomes fully empty, columns to its
   right shift left to close the horizontal gap. The grid is represented as
   an array of bottom-up color stacks, left→right, with empty columns
   simply absent — this single representation gets BOTH gravity phases for
   free (see msApplyTap): filtering removed indices out of a column while
   keeping the rest in order IS vertical gravity, and dropping zero-length
   columns from the outer array IS horizontal compaction.

   Win condition: the entire grid cleared to empty (not "reveal a picture
   underneath" — there is no hidden image).

   Move budget: each level ships a fixed number of allowed taps, pre-
   verified solvable-to-empty within that budget. Running out of moves
   with pixels remaining is a stuck state — never persisted, always
   recomputed live (see msIsStuck) — with a toast pointing at the existing
   Restart button, same as Water Sort/Parkplatz's precedent.

   Extra-moves-via-question mechanic (mirrors Water Sort's extra-bottle /
   Parkplatz's extra-bay mechanic exactly): answering a quiz question via
   the shared askQuestions() grants +1 allowed move, capped at
   MS_MAX_EXTRA_MOVES. askQuestions() feeds the Tamagotchi automatically on
   every correct answer, same as every other question-spending flow.

   Levels are static data (MS_LEVELS below), generated offline by
   scripts/generate-mosaik-levels.js via deal-a-random-board +
   independently re-verify-with-a-real-solver + retry-on-failure (NOT a
   correct-by-construction method — see that script's header comment for
   why a clean constructive approach isn't a good fit for gravity-based
   clear games). Only the shuffled play order/position and the LIVE
   in-progress grid/move state are persisted in the save; level layouts
   ship with the app.
══════════════════════════════════════════════════════════ */

const MS_COLORS = ["#e0413a", "#5aa8e8", "#6fd88a", "#e8d95a", "#b06fe8", "#e86fb0"];
const MS_MAX_EXTRA_MOVES = 3; // matches Water Sort's WS_MAX_EXTRA_BOTTLES

// Generated by scripts/generate-mosaik-levels.js. Per level:
// g=[rows,cols]; mv=default move budget; grid=flat colorIdx array, row-major,
// TOP row first, left→right (grid.length === rows*cols).
const MS_LEVELS = [{"g":[4,4],"mv":7,"grid":[1,1,2,2,0,2,0,2,0,2,0,0,0,0,1,2]},{"g":[4,4],"mv":7,"grid":[1,0,2,1,1,0,2,1,0,2,1,0,0,1,1,2]},{"g":[4,4],"mv":7,"grid":[1,0,0,1,0,0,0,2,1,2,2,2,1,2,2,0]},{"g":[4,4],"mv":7,"grid":[1,1,0,1,2,2,0,0,0,0,0,2,1,1,1,1]},{"g":[4,4],"mv":7,"grid":[0,2,0,2,0,2,0,2,0,1,1,1,2,1,1,1]},{"g":[4,4],"mv":7,"grid":[1,0,1,1,0,0,2,0,0,1,2,0,1,2,1,0]},{"g":[4,4],"mv":7,"grid":[0,1,2,2,1,2,1,1,2,2,1,1,0,1,1,1]},{"g":[4,4],"mv":7,"grid":[0,1,1,1,1,1,2,0,1,1,2,1,0,0,1,1]},{"g":[4,4],"mv":7,"grid":[0,2,1,1,0,2,2,1,0,0,0,0,2,0,0,0]},{"g":[4,4],"mv":7,"grid":[1,1,2,1,0,2,2,0,1,1,2,2,1,1,1,1]},{"g":[4,4],"mv":7,"grid":[1,2,2,0,2,1,1,2,2,1,0,0,0,2,2,1]},{"g":[4,4],"mv":7,"grid":[1,1,0,0,1,0,0,1,1,1,2,0,0,0,2,0]},{"g":[4,4],"mv":7,"grid":[2,0,1,1,2,1,1,0,2,0,1,1,0,0,1,0]},{"g":[4,4],"mv":7,"grid":[0,0,1,0,1,2,0,2,2,1,1,2,2,1,2,2]},{"g":[4,4],"mv":7,"grid":[1,0,0,1,1,2,2,0,2,0,1,0,2,2,1,0]},{"g":[5,5],"mv":10,"grid":[0,1,2,1,1,1,1,0,0,2,0,2,2,2,0,1,1,2,2,1,2,2,2,2,1]},{"g":[5,5],"mv":10,"grid":[1,2,0,0,2,1,1,0,2,2,2,2,0,1,1,0,1,0,0,2,1,1,0,0,0]},{"g":[5,5],"mv":10,"grid":[2,0,0,1,1,0,1,0,1,2,1,1,0,0,1,0,2,1,1,2,2,2,1,1,2]},{"g":[5,5],"mv":10,"grid":[2,2,0,0,2,1,0,2,2,0,1,2,0,0,2,1,2,1,0,2,0,0,0,1,1]},{"g":[5,5],"mv":10,"grid":[2,0,0,2,1,1,0,1,0,0,2,0,0,0,0,1,0,0,2,1,2,0,1,2,1]},{"g":[5,5],"mv":10,"grid":[1,1,2,0,0,0,0,1,2,2,0,1,1,1,1,1,0,2,0,2,2,1,2,0,1]},{"g":[5,5],"mv":10,"grid":[2,2,2,2,0,0,1,0,1,1,0,2,2,1,1,1,1,2,1,0,0,1,2,2,1]},{"g":[5,5],"mv":10,"grid":[1,1,0,0,2,0,2,1,0,0,1,2,1,0,1,0,0,1,2,0,0,0,2,2,0]},{"g":[5,5],"mv":10,"grid":[2,0,1,2,0,2,1,2,1,2,0,2,1,2,2,0,0,2,2,0,1,2,2,0,1]},{"g":[5,5],"mv":10,"grid":[0,2,1,0,0,1,2,0,1,0,1,1,0,2,1,0,2,2,2,0,0,0,1,2,0]},{"g":[5,5],"mv":10,"grid":[2,2,0,0,1,0,1,0,2,0,0,0,2,2,0,0,1,1,0,0,1,2,1,2,1]},{"g":[5,5],"mv":10,"grid":[0,2,2,1,2,2,2,0,0,2,2,1,1,0,0,2,0,0,0,0,0,2,1,0,2]},{"g":[5,5],"mv":10,"grid":[0,0,0,0,2,0,1,2,1,2,1,0,0,1,1,0,1,2,0,1,2,2,2,2,0]},{"g":[5,5],"mv":10,"grid":[0,2,0,0,0,0,1,0,2,1,1,0,0,2,2,2,0,0,1,0,1,0,1,1,0]},{"g":[5,5],"mv":10,"grid":[0,0,1,0,2,1,1,1,2,0,0,2,2,2,0,1,1,0,0,0,0,0,0,1,1]},{"g":[5,5],"mv":12,"grid":[2,1,1,1,2,0,3,3,0,0,3,3,2,0,3,3,3,0,0,0,1,3,1,3,3]},{"g":[5,5],"mv":12,"grid":[0,0,0,2,3,0,1,3,2,0,3,0,3,0,1,1,3,0,0,2,0,1,0,2,0]},{"g":[5,5],"mv":12,"grid":[1,0,3,2,2,1,0,3,2,2,0,2,0,2,0,3,3,3,2,0,0,0,2,1,0]},{"g":[5,5],"mv":12,"grid":[3,1,2,0,0,2,2,0,2,1,2,3,1,0,0,3,1,2,0,0,0,3,3,3,3]},{"g":[5,5],"mv":12,"grid":[0,2,1,3,2,1,2,2,1,3,2,1,3,2,1,2,0,0,3,3,2,1,1,1,1]},{"g":[5,5],"mv":12,"grid":[1,2,1,3,3,0,1,2,3,3,0,0,1,2,3,0,1,3,3,1,1,1,3,3,1]},{"g":[5,5],"mv":12,"grid":[1,0,1,1,2,2,2,1,1,2,1,0,3,0,1,2,2,1,0,2,1,3,1,1,1]},{"g":[5,5],"mv":12,"grid":[0,2,2,2,3,3,2,3,1,0,1,2,3,1,3,1,1,0,0,0,0,1,2,0,1]},{"g":[5,5],"mv":12,"grid":[0,2,2,3,3,3,0,3,1,2,1,1,0,1,0,2,2,1,3,2,1,0,0,2,2]},{"g":[5,5],"mv":12,"grid":[0,3,1,1,0,3,2,2,1,1,1,0,0,2,0,2,0,1,3,1,2,3,2,3,2]},{"g":[5,5],"mv":12,"grid":[3,3,0,3,2,1,3,2,0,0,1,0,3,1,0,3,0,1,0,0,2,1,3,3,1]},{"g":[5,5],"mv":12,"grid":[2,2,1,0,1,1,0,3,3,2,2,3,0,2,2,2,1,2,2,0,3,2,0,1,0]},{"g":[5,5],"mv":12,"grid":[3,2,3,3,2,0,1,1,0,3,3,1,3,3,3,0,0,1,2,2,0,3,1,1,2]},{"g":[5,5],"mv":12,"grid":[1,0,0,3,0,3,3,1,0,2,2,2,1,0,2,0,2,0,3,3,0,2,2,0,0]},{"g":[5,5],"mv":12,"grid":[1,2,3,2,1,1,0,2,3,2,1,0,2,1,1,2,3,1,2,0,2,1,2,3,0]},{"g":[6,6],"mv":15,"grid":[1,0,3,3,2,3,1,1,3,0,2,1,1,3,0,2,1,0,0,3,3,0,3,3,3,0,0,0,0,1,0,0,3,2,1,0]},{"g":[6,6],"mv":15,"grid":[1,2,0,1,3,1,0,2,3,3,0,1,1,3,2,2,1,0,3,3,1,1,1,2,0,0,3,0,2,3,0,0,2,3,1,2]},{"g":[6,6],"mv":15,"grid":[0,2,1,3,2,1,0,0,1,0,3,3,3,2,0,0,3,3,1,1,2,1,3,2,3,1,0,3,0,2,2,2,0,1,0,2]},{"g":[6,6],"mv":15,"grid":[0,2,2,2,2,2,1,0,3,3,0,0,3,0,0,1,1,2,2,3,3,1,2,2,3,3,3,2,0,3,2,3,3,3,3,0]},{"g":[6,6],"mv":15,"grid":[2,0,0,1,2,1,3,2,0,0,3,1,1,3,2,2,0,1,2,3,2,3,3,1,2,2,1,1,3,0,2,0,0,2,1,0]},{"g":[6,6],"mv":15,"grid":[0,0,3,2,0,2,0,2,3,0,2,0,1,1,3,1,1,1,2,3,2,1,2,2,0,1,0,3,3,2,2,1,0,1,3,2]},{"g":[6,6],"mv":15,"grid":[1,0,2,0,1,3,3,0,3,0,2,1,3,0,2,3,1,2,3,2,0,3,2,1,2,1,0,0,2,0,1,1,1,0,3,0]},{"g":[6,6],"mv":15,"grid":[3,2,0,2,2,1,2,3,0,0,2,2,1,3,3,2,2,1,2,0,0,3,1,1,0,0,0,1,3,1,2,1,3,1,1,1]},{"g":[6,6],"mv":15,"grid":[2,2,3,3,3,2,1,1,1,3,2,2,1,1,2,1,0,0,2,3,2,2,0,2,0,3,0,2,0,0,0,0,0,3,2,2]},{"g":[6,6],"mv":15,"grid":[2,2,2,0,1,2,0,0,1,0,1,2,3,1,1,2,0,0,3,2,2,1,2,1,3,0,2,0,3,3,2,0,0,0,2,1]},{"g":[6,6],"mv":15,"grid":[0,1,3,0,2,3,3,2,3,3,2,1,2,0,2,2,0,1,2,2,2,3,1,0,2,0,0,1,3,1,3,3,0,0,3,2]},{"g":[6,6],"mv":15,"grid":[2,1,0,2,3,1,2,0,1,1,3,2,3,1,1,3,1,1,1,2,3,0,2,1,2,2,0,1,3,3,1,1,1,3,2,0]},{"g":[6,6],"mv":15,"grid":[1,1,0,2,2,0,3,2,2,2,0,0,2,3,0,0,2,1,1,0,3,1,2,2,3,1,3,0,3,2,0,3,3,0,2,0]},{"g":[6,6],"mv":15,"grid":[3,1,2,0,1,2,0,3,1,3,0,0,3,0,3,1,0,3,3,2,0,2,2,3,0,3,2,0,3,0,2,3,2,0,1,1]},{"g":[6,6],"mv":15,"grid":[0,3,2,1,3,2,3,1,3,3,3,0,1,2,3,0,3,2,3,1,2,3,1,1,1,2,0,0,0,2,3,2,1,2,0,3]},{"g":[6,6],"mv":17,"grid":[0,3,0,0,1,2,4,0,0,1,3,2,0,3,1,2,1,2,4,1,3,4,2,0,1,0,4,1,2,2,3,0,1,4,4,2]},{"g":[6,6],"mv":17,"grid":[0,0,4,0,1,2,4,0,2,2,1,2,1,2,4,1,2,0,0,0,1,0,4,4,4,3,3,2,2,0,2,3,3,1,2,0]},{"g":[6,6],"mv":17,"grid":[0,3,3,3,3,4,0,2,3,0,2,0,1,0,3,3,4,4,0,0,2,2,4,0,4,0,3,1,2,1,4,0,3,1,1,2]},{"g":[6,6],"mv":17,"grid":[2,4,0,2,2,4,1,1,3,4,2,2,0,0,0,0,4,1,0,2,4,3,4,0,1,0,3,4,0,1,1,4,1,0,0,2]},{"g":[6,6],"mv":17,"grid":[0,2,1,3,0,0,2,2,1,3,2,4,4,0,4,4,0,2,2,2,0,3,4,2,0,0,1,1,3,1,1,2,3,3,4,1]},{"g":[6,6],"mv":17,"grid":[4,2,2,2,4,0,3,2,2,4,0,0,0,0,1,1,3,0,3,0,2,4,2,0,4,2,1,4,3,2,2,0,0,4,3,4]},{"g":[6,6],"mv":17,"grid":[4,0,2,3,0,0,2,3,2,1,1,3,2,4,3,2,2,1,4,1,2,2,0,2,4,3,4,4,1,0,2,1,4,3,0,3]},{"g":[6,6],"mv":17,"grid":[0,3,1,0,1,3,1,1,4,2,4,2,1,2,1,3,1,3,4,3,0,3,0,1,1,0,2,3,2,4,1,2,3,0,3,1]},{"g":[6,6],"mv":17,"grid":[3,2,3,1,0,3,2,1,4,1,1,0,2,3,3,4,3,0,3,2,1,0,3,2,0,1,0,0,1,0,0,1,3,4,1,2]},{"g":[6,6],"mv":17,"grid":[0,1,2,1,1,0,0,3,4,2,1,0,3,1,1,0,3,4,4,1,4,3,1,1,2,1,2,3,3,0,1,4,4,1,3,0]},{"g":[7,7],"mv":20,"grid":[0,0,2,3,0,4,2,3,0,1,1,4,4,4,1,4,4,3,4,2,2,3,1,0,2,2,2,0,2,4,0,0,4,0,1,0,4,3,3,0,3,4,1,4,2,0,3,3,0]},{"g":[7,7],"mv":20,"grid":[0,4,0,3,1,1,1,1,2,3,3,1,1,1,1,1,0,1,2,1,4,1,2,4,4,0,3,3,4,0,1,3,2,1,2,3,0,2,2,1,0,0,2,2,4,2,2,0,0]},{"g":[7,7],"mv":20,"grid":[4,0,2,3,3,4,3,3,1,4,2,4,3,4,4,3,4,2,3,1,1,3,4,4,0,4,2,1,3,1,1,3,0,1,1,3,4,3,2,4,3,2,4,3,0,1,2,4,2]},{"g":[7,7],"mv":20,"grid":[1,0,2,4,2,0,1,3,2,1,1,4,4,4,4,2,0,3,3,3,2,3,0,2,0,4,0,3,2,2,1,1,0,1,0,0,4,4,1,1,1,2,0,3,1,1,3,1,2]},{"g":[7,7],"mv":20,"grid":[3,3,1,0,2,1,3,4,4,3,3,3,4,3,4,2,4,4,1,1,2,4,0,4,4,3,3,3,0,4,3,4,3,2,1,0,3,3,3,4,4,1,2,3,4,1,1,4,3]},{"g":[7,7],"mv":20,"grid":[3,4,2,4,1,3,4,4,2,0,4,1,3,4,2,2,4,4,1,1,0,0,2,3,0,2,0,0,4,2,1,1,4,0,0,4,1,4,3,3,2,0,4,3,4,3,3,1,1]},{"g":[7,7],"mv":20,"grid":[1,4,4,0,0,1,3,0,1,3,3,4,1,4,0,3,3,0,0,0,3,0,0,4,0,1,2,1,1,0,0,2,2,1,0,3,4,0,0,0,3,3,4,0,4,2,0,0,1]},{"g":[7,7],"mv":20,"grid":[1,0,0,3,0,0,1,4,3,0,4,2,1,3,1,2,4,3,1,3,1,4,2,1,1,2,0,0,3,2,0,0,4,0,0,0,0,4,4,0,3,1,1,3,0,0,4,0,3]},{"g":[7,7],"mv":20,"grid":[4,0,3,2,2,3,1,3,0,4,2,2,4,4,3,4,2,4,3,1,1,2,4,4,0,0,4,4,0,4,4,2,2,2,2,0,3,0,1,2,0,0,3,2,4,3,0,2,0]},{"g":[7,7],"mv":20,"grid":[3,0,3,2,0,2,0,1,2,3,2,1,0,3,0,3,3,4,0,4,1,4,3,4,2,4,4,3,0,3,0,0,0,3,3,2,2,0,2,3,1,1,0,0,3,1,0,3,2]}];
const MS_LEVEL_COUNT = MS_LEVELS.length;

function msGenerateLevel(levelIndex) {
  const level = MS_LEVELS[levelIndex];
  const [rows, cols] = level.g;
  return { rows, cols, moveBudget: level.mv, grid: level.grid };
}
function msColumnsFromGrid(grid, rows, cols) {
  const columns = [];
  for (let c = 0; c < cols; c++) {
    const col = [];
    for (let r = rows - 1; r >= 0; r--) col.push(grid[r * cols + c]); // bottom-up
    columns.push(col);
  }
  return columns;
}

/* ══════════════════════════════════════════════════════════
   CORE PURE LOGIC — no DOM/globals, reused verbatim by
   scripts/generate-mosaik-levels.js and scripts/verify-mosaik-levels.js
   via the module.exports guard at the bottom of this file.
══════════════════════════════════════════════════════════ */
function msGroupAt(columns, col, idx) {
  const startColor = columns[col] && columns[col][idx];
  if (startColor == null) return [];
  const seen = new Set();
  const stack = [[col, idx]];
  const cells = [];
  while (stack.length) {
    const [c, i] = stack.pop();
    const k = c + ':' + i;
    if (seen.has(k)) continue;
    if (!columns[c] || columns[c][i] !== startColor) continue;
    seen.add(k);
    cells.push([c, i]);
    if (columns[c][i - 1] !== undefined) stack.push([c, i - 1]);
    if (columns[c][i + 1] !== undefined) stack.push([c, i + 1]);
    if (columns[c - 1] && columns[c - 1][i] !== undefined) stack.push([c - 1, i]);
    if (columns[c + 1] && columns[c + 1][i] !== undefined) stack.push([c + 1, i]);
  }
  return cells;
}

function msFindAllGroups(columns) {
  const seen = new Set();
  const groups = [];
  for (let c = 0; c < columns.length; c++) {
    for (let i = 0; i < columns[c].length; i++) {
      const k = c + ':' + i;
      if (seen.has(k)) continue;
      const cells = msGroupAt(columns, c, i);
      cells.forEach(([cc, ii]) => seen.add(cc + ':' + ii));
      if (cells.length >= 2) groups.push({ col: c, idx: i, size: cells.length, color: columns[c][i] });
    }
  }
  return groups;
}

// The only player-facing transition. Returns null for a tap on an isolated
// (group size < 2) pixel — rejected tap, no state change.
function msApplyTap(columns, col, idx) {
  const cells = msGroupAt(columns, col, idx);
  if (cells.length < 2) return null;
  const removeByCol = new Map();
  for (const [c, i] of cells) {
    if (!removeByCol.has(c)) removeByCol.set(c, new Set());
    removeByCol.get(c).add(i);
  }
  const newColumns = [];
  for (let c = 0; c < columns.length; c++) {
    const removeSet = removeByCol.get(c);
    const newCol = removeSet ? columns[c].filter((_, i) => !removeSet.has(i)) : columns[c].slice();
    if (newCol.length > 0) newColumns.push(newCol);
  }
  return { columns: newColumns, cleared: cells.length };
}

function msIsCleared(columns) { return columns.length === 0; }
function msDistinctColorCount(columns) {
  const set = new Set();
  for (const col of columns) for (const v of col) set.add(v);
  return set.size;
}
function msStateKey(columns) { return columns.map(col => col.join(',')).join('|'); }

function msIsStuck(columns, movesRemaining) {
  if (columns.length === 0) return false;
  if (movesRemaining <= 0) return true;
  return msFindAllGroups(columns).length === 0; // every remaining cell isolated
}

/* ── solver: iterative-deepening DFS with real pruning (largest-group-first
   ordering, admissible per-color lower bound, memoized dead states keyed
   by movesLeft, node-visit budget cap) — see js/mosaik.js's generation
   script header and the plan for full rationale. ── */
function msDfsSolve(columns, moveBudget, nodeBudget) {
  const dead = new Set();
  let visited = 0, aborted = false;
  const path = [];
  function dfs(state, movesLeft) {
    if (state.length === 0) return true;
    if (movesLeft === 0) return false;
    if (nodeBudget && ++visited > nodeBudget) { aborted = true; return false; }
    if (msDistinctColorCount(state) > movesLeft) return false;
    const key = msStateKey(state) + '@' + movesLeft;
    if (dead.has(key)) return false;
    const groups = msFindAllGroups(state).sort((a, b) => b.size - a.size);
    for (const g of groups) {
      if (aborted) break;
      const result = msApplyTap(state, g.col, g.idx);
      path.push([g.col, g.idx]);
      if (dfs(result.columns, movesLeft - 1)) return true;
      path.pop();
    }
    if (!aborted) dead.add(key);
    return false;
  }
  const solvable = dfs(columns, moveBudget);
  return { solvable, moves: solvable ? path.slice() : null, aborted, visited };
}

// Fast path, not a shortcut around real verification: a greedy playout that
// empties the board within budget is a concrete, replayable,
// deterministically-checkable solution — exactly as legitimate as a
// DFS-found one, just usually faster to find. Greedy FAILING proves
// nothing and never causes rejection on its own.
function msGreedyPlayout(columns, moveBudget, rng) {
  let state = columns.map(c => c.slice());
  const moves = [];
  for (let m = 0; m < moveBudget; m++) {
    if (state.length === 0) return { solved: true, moves };
    const groups = msFindAllGroups(state);
    if (!groups.length) return { solved: false, moves };
    const maxSize = Math.max(...groups.map(g => g.size));
    const best = groups.filter(g => g.size === maxSize);
    const pick = best[Math.floor(rng() * best.length)];
    state = msApplyTap(state, pick.col, pick.idx).columns;
    moves.push([pick.col, pick.idx]);
  }
  return { solved: state.length === 0, moves };
}

function msSolve(columns, moveBudget, opts) {
  const { rng = Math.random, greedyAttempts = 60, nodeBudget = 400000 } = opts || {};
  for (let a = 0; a < greedyAttempts; a++) {
    const g = msGreedyPlayout(columns, moveBudget, rng);
    if (g.solved) return { solvable: true, moves: g.moves, aborted: false, method: 'greedy' };
  }
  let remainingBudget = nodeBudget;
  for (let k = msDistinctColorCount(columns); k <= moveBudget; k++) {
    const result = msDfsSolve(columns, k, remainingBudget);
    remainingBudget -= result.visited || 0;
    if (result.solvable) return { solvable: true, moves: result.moves, aborted: false, method: 'dfs' };
    if (result.aborted || remainingBudget <= 0) return { solvable: false, moves: null, aborted: true, method: 'dfs' };
  }
  return { solvable: false, moves: null, aborted: false, method: 'dfs' };
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.mosaik
══════════════════════════════════════════════════════════ */
// Transient, purely-visual state for msRender() — never persisted in G.
let msAnimating = false;     // input lock during the dissolve defer window
let msLastFallCols = null;   // Set of post-tap column indices to play the "settled" cue on

function msOnCellTap(col, h) {
  if (msAnimating) return;
  const ms = G.mosaik;
  if (ms.currentLevelIndex == null) return;
  const level = msGenerateLevel(ms.currentLevelIndex);
  const movesRemaining = level.moveBudget + (ms.extraMovesBought || 0) - ms.movesUsed;
  if (movesRemaining <= 0) { showToast("🧱 Keine Züge mehr — versuch's mit 🔄 Neu starten!"); return; }
  const cells = msGroupAt(ms.columns, col, h); // same lookup msApplyTap does internally
  if (cells.length < 2) return; // isolated pixel — rejected tap, no state/visual change
  const result = msApplyTap(ms.columns, col, h);

  msAnimating = true;
  msPlayDissolveAnimation(cells, ms.columns, result.columns, () => {
    msAnimating = false;
    ms.columns = result.columns;
    ms.movesUsed++;
    saveState(); // explicit — mid-level progress must survive a reload
    if (msIsCleared(ms.columns)) { msOnLevelSolved(); return; }
    if (msIsStuck(ms.columns, level.moveBudget + (ms.extraMovesBought || 0) - ms.movesUsed)) {
      showToast("🧱 Feststeckt — versuch's mit 🔄 Neu starten!");
    }
    msRender();
  });
}

// Animates the currently-mounted cells about to be removed (dissolve: scale
// down + fade), then calls onDone. Also computes which POST-tap column
// indices had any removal, so msRender() can play a "just settled" cue on
// their surviving cells — a simpler stand-in for exact per-pixel fall-
// distance physics (that would need full FLIP-style before/after position
// tracking), but still reads as "these pixels fell into place."
function msPlayDissolveAnimation(cells, oldColumns, newColumns, onDone) {
  let found = false;
  cells.forEach(([c, i]) => {
    const el = document.querySelector(`#ms-grid .ms-cell[data-col="${c}"][data-h="${i}"]`);
    if (el) { el.classList.add('ms-cell--dissolving'); found = true; }
  });

  // Map each original column index to its post-tap index: msApplyTap only
  // keeps columns with >=1 surviving cell, in their original relative
  // order, so an original column's new index is just a running counter
  // over the columns that survived non-empty.
  const removedCountByCol = new Map();
  for (const [c] of cells) removedCountByCol.set(c, (removedCountByCol.get(c) || 0) + 1);
  const fallCols = new Set();
  let newIdx = 0;
  for (let c = 0; c < oldColumns.length; c++) {
    const survivingCount = oldColumns[c].length - (removedCountByCol.get(c) || 0);
    if (survivingCount <= 0) continue; // whole column removed — no output index to animate
    if (removedCountByCol.has(c)) fallCols.add(newIdx);
    newIdx++;
  }
  msLastFallCols = fallCols;

  if (!found) { onDone(); return; }
  setTimeout(onDone, 260);
}

function msOnLevelSolved() {
  G.stats.mosaikLevelsCompleted = (G.stats.mosaikLevelsCompleted || 0) + 1;
  checkTrophies();
  showToast("🧩 Mosaik gelöst!");
  saveState();
  msRender();
  setTimeout(msAdvanceToNextLevel, 900);
}

function msAdvanceToNextLevel() {
  const ms = G.mosaik;
  ms.playOrderPos++;
  if (ms.playOrderPos >= ms.playOrder.length) {
    const prevLast = ms.playOrder[ms.playOrder.length - 1];
    const order = shuffleArray([...Array(MS_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    ms.playOrder = order;
    ms.playOrderPos = 0;
  }
  msStartLevel(ms.playOrder[ms.playOrderPos]);
}

function msStartLevel(levelIndex) {
  const ms = G.mosaik;
  const level = msGenerateLevel(levelIndex);
  ms.currentLevelIndex = levelIndex;
  ms.columns = msColumnsFromGrid(level.grid, level.rows, level.cols);
  ms.movesUsed = 0;
  ms.extraMovesBought = 0;
  msAnimating = false;
  msLastFallCols = null;
  saveState();
  msRender();
}

function msRestartLevel() {
  const ms = G.mosaik;
  if (ms.currentLevelIndex == null) return;
  msStartLevel(ms.currentLevelIndex);
  showToast("🔄 Level neu gestartet.");
}

function msEnsureQueueAndLevel() {
  const ms = G.mosaik;
  if (!ms.playOrder.length) {
    ms.playOrder = shuffleArray([...Array(MS_LEVEL_COUNT).keys()]);
    ms.playOrderPos = 0;
  }
  if (ms.currentLevelIndex == null || !ms.columns.length) {
    msStartLevel(ms.playOrder[ms.playOrderPos]);
  } else {
    msRender();
  }
}

function msBuyExtraMove() {
  const ms = G.mosaik;
  if ((ms.extraMovesBought || 0) >= MS_MAX_EXTRA_MOVES) {
    showToast(`Maximal ${MS_MAX_EXTRA_MOVES} Extra-Züge pro Level!`);
    return;
  }
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🧩 Extra-Zug", 1, () => {
    ms.extraMovesBought = (ms.extraMovesBought || 0) + 1;
    G.stats.mosaikExtraMovesBought = (G.stats.mosaikExtraMovesBought || 0) + 1;
    checkTrophies();
    saveState();
    msRender();
    showToast("🧩 Extra-Zug erhalten!");
  }, null);
}

/* ══════════════════════════════════════════════════════════
   RENDERING — full innerHTML rebuild + re-bind onclick each call, per this
   app's established convention (no incremental DOM diffing anywhere).
══════════════════════════════════════════════════════════ */
function msRender() {
  const ms = G.mosaik;
  if (ms.currentLevelIndex == null) return;
  const level = msGenerateLevel(ms.currentLevelIndex);
  const infoEl = document.getElementById("ms-level-info");
  const gridEl = document.getElementById("ms-grid");
  const buyBtn = document.getElementById("ms-buy-move-btn");
  if (!gridEl) return;

  const movesRemaining = Math.max(0, level.moveBudget + (ms.extraMovesBought || 0) - ms.movesUsed);
  if (infoEl) {
    infoEl.textContent = `Level ${ms.currentLevelIndex + 1} / ${MS_LEVEL_COUNT} · 🎯 ${movesRemaining} Zug${movesRemaining === 1 ? '' : 'e'} übrig`;
  }

  const fallCols = msLastFallCols;
  msLastFallCols = null; // consume — a later, unrelated render must not replay it

  const { rows, cols } = level;
  gridEl.style.cssText = `grid-template-columns:repeat(${cols},1fr);grid-template-rows:repeat(${rows},1fr);`;
  const cellsHtml = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const stackIdx = rows - 1 - r;
      const col = ms.columns[c];
      const val = col && stackIdx < col.length ? col[stackIdx] : null;
      if (val == null) { cellsHtml.push(`<div class="ms-cell ms-cell--floor"></div>`); continue; }
      const falling = fallCols && fallCols.has(c);
      // bottom-most surviving cells (small stackIdx) settle first; cells
      // that were higher up land slightly later, suggesting a fall
      const style = falling
        ? `background:${MS_COLORS[val]};animation-delay:${stackIdx * 25}ms;`
        : `background:${MS_COLORS[val]};`;
      cellsHtml.push(`<div class="ms-cell${falling ? ' ms-cell--falling' : ''}" style="${style}" data-col="${c}" data-h="${stackIdx}"></div>`);
    }
  }
  gridEl.innerHTML = cellsHtml.join("");
  gridEl.querySelectorAll(".ms-cell:not(.ms-cell--floor)").forEach(el => {
    el.onclick = () => msOnCellTap(parseInt(el.dataset.col, 10), parseInt(el.dataset.h, 10));
  });

  if (buyBtn) {
    const atCap = (ms.extraMovesBought || 0) >= MS_MAX_EXTRA_MOVES;
    buyBtn.disabled = atCap;
    buyBtn.classList.toggle("ws-buy-bottle-btn--off", atCap);
    buyBtn.textContent = atCap
      ? "➕ Maximal erreicht"
      : `➕ Extra-Zug (1 Frage) · ${ms.extraMovesBought || 0}/${MS_MAX_EXTRA_MOVES}`;
  }
}

if (typeof window !== 'undefined') {
  window.msOnCellTap = msOnCellTap;
  window.msRestartLevel = msRestartLevel;
  window.msEnsureQueueAndLevel = msEnsureQueueAndLevel;
  window.msBuyExtraMove = msBuyExtraMove;
  window.msRender = msRender;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    MS_COLORS, MS_LEVELS, MS_LEVEL_COUNT, MS_MAX_EXTRA_MOVES,
    msGenerateLevel, msColumnsFromGrid,
    msGroupAt, msFindAllGroups, msApplyTap, msIsCleared, msDistinctColorCount,
    msStateKey, msIsStuck, msDfsSolve, msGreedyPlayout, msSolve,
  };
}
