'use strict';

/* ══════════════════════════════════════════════════════════
   PARKPLATZ — passenger-matching parking-jam puzzle

   A parking lot of single-cell cars, each with one fixed exit direction,
   sits next to a queue of colored passengers. Tapping a car releases it
   into the first open loading bay — but only if the path from its cell to
   its exit direction is completely clear of other still-parked cars (cars
   never reposition; a car is strictly parked or released, never in
   between). The instant a bay's car color matches the front of the queue,
   that passenger boards automatically (front-of-queue only — a matching
   passenger further back must wait its turn); a car whose seats all fill
   departs, freeing its bay.

   Unlike Rush Hour (this mini-game's first, wrong-genre attempt — see git
   history), a car's state is binary, so the state graph is a DAG (monotonic
   release, never reversible) and every solution takes exactly carCount
   releases — there's no "shortest path" to hunt for. Levels are generated
   *constructively* (scripts/generate-parking-levels.js): a valid release
   order and its exact matching passenger queue are built together via
   forward simulation, so a level is correct by construction rather than
   found via deal-and-reject, and then independently re-verified with the
   real DFS solver below before being accepted.

   Extra bays mechanic (mirrors Water Sort's extra-bottle mechanic): each
   level's number of loading bays equals its count of distinct passenger
   colors; only `db` (a level's default bay count) are unlocked for free,
   the rest unlock one at a time, each costing one quiz question via the
   shared askQuestions() (which also feeds the Tamagotchi automatically,
   same as every other question-spending flow in this app). Opening more
   bays only ever adds legal moves, so a level is always solvable with just
   its default bays — extra bays are pure relief for a stuck player.

   Levels are static data (PL_LEVELS below), generated offline, never live
   in the browser. Only the shuffled play order, position in it, and the
   live in-progress lot/bay/queue state are persisted in the save; the
   level layouts themselves ship with the app.
══════════════════════════════════════════════════════════ */

const PL_COLORS = [
  "#e0413a", "#5aa8e8", "#6fd88a", "#e8d95a", "#b06fe8",
  "#e86fb0", "#5adfd0", "#e8a45a", "#8a9be0", "#c9a857",
];
const PL_DIR_GLYPH = ["▲", "▶", "▼", "◀"]; // 0=up,1=right,2=down,3=left — direction driven toward the edge

// Generated by scripts/generate-parking-levels.js. Per level:
// g=[rows,cols]; db=default (pre-unlocked) bay count;
// cars=[row,col,dirIdx(0=up,1=right,2=down,3=left),colorIdx,seats][];
// q=passenger queue, ordered, front=index 0, as colorIdx values.
const PL_LEVELS = [{"g":[3,4],"db":1,"cars":[[1,3,0,1,2],[0,3,1,0,2],[0,2,0,1,2],[2,3,2,0,2]],"q":[0,0,0,0,1,1,1,1]},{"g":[3,4],"db":1,"cars":[[0,2,3,0,2],[2,3,2,1,2],[1,3,1,1,2],[0,0,3,0,2]],"q":[1,1,0,0,1,1,0,0]},{"g":[3,4],"db":1,"cars":[[1,2,1,0,2],[0,0,2,0,2],[2,3,0,0,2],[2,1,0,1,2]],"q":[0,0,1,1,0,0,0,0]},{"g":[3,4],"db":1,"cars":[[1,0,0,1,2],[1,2,3,1,2],[0,2,0,1,2],[0,3,0,1,2]],"q":[1,1,1,1,1,1,1,1]},{"g":[3,4],"db":1,"cars":[[1,3,1,0,2],[0,3,3,0,2],[1,1,1,1,2],[0,0,2,0,2]],"q":[0,0,0,0,0,0,1,1]},{"g":[3,4],"db":1,"cars":[[1,1,1,0,2],[2,3,2,1,2],[1,2,0,1,2],[0,0,2,0,2]],"q":[1,1,0,0,0,0,1,1]},{"g":[3,4],"db":1,"cars":[[2,1,1,1,2],[2,3,0,0,2],[0,2,2,0,2],[1,1,1,1,2]],"q":[0,0,0,0,1,1,1,1]},{"g":[3,4],"db":1,"cars":[[1,2,2,1,2],[2,1,1,1,2],[2,0,2,0,2],[1,3,2,0,2]],"q":[1,1,1,1,0,0,0,0]},{"g":[3,4],"db":1,"cars":[[1,1,3,0,2],[1,0,3,0,2],[1,2,2,1,2],[1,3,2,1,2]],"q":[0,0,1,1,0,0,1,1]},{"g":[3,4],"db":1,"cars":[[0,0,2,0,2],[2,2,3,1,2],[0,1,0,1,2],[0,2,2,0,2]],"q":[0,0,1,1,1,1,0,0]},{"g":[3,4],"db":1,"cars":[[2,1,0,1,2],[0,0,0,1,2],[0,1,3,1,2],[1,0,3,0,2]],"q":[0,0,1,1,1,1,1,1]},{"g":[3,4],"db":1,"cars":[[2,1,0,1,2],[0,2,1,1,2],[1,1,0,0,2],[1,0,3,0,2]],"q":[1,1,0,0,0,0,1,1]},{"g":[3,4],"db":1,"cars":[[2,3,3,0,2],[1,1,1,0,2],[2,2,0,1,2],[0,3,2,0,2]],"q":[1,1,0,0,0,0,0,0]},{"g":[3,4],"db":1,"cars":[[2,3,2,0,2],[0,0,3,0,2],[2,0,3,0,2],[0,2,3,0,2]],"q":[0,0,0,0,0,0,0,0]},{"g":[3,4],"db":1,"cars":[[2,2,3,1,2],[0,1,3,1,2],[2,0,3,0,2],[2,3,1,1,2]],"q":[1,1,1,1,0,0,1,1]},{"g":[4,4],"db":2,"cars":[[2,1,1,2,3],[3,0,2,2,3],[2,0,3,0,3],[1,0,3,2,3],[3,3,1,1,3],[0,1,3,2,3]],"q":[0,0,0,1,2,1,2,2,1,2,2,2,2,2,2,2,2,2]},{"g":[4,4],"db":2,"cars":[[0,3,3,1,2],[2,2,2,2,2],[2,1,2,0,3],[0,1,0,0,3],[0,0,0,1,2],[3,1,2,1,3]],"q":[0,0,1,0,1,1,1,1,1,1,0,0,0,2,2]},{"g":[4,4],"db":2,"cars":[[2,0,0,2,2],[2,1,3,1,3],[2,3,2,0,3],[2,2,2,0,2],[0,2,3,1,2],[3,0,3,1,2]],"q":[1,1,0,0,1,1,2,2,1,1,0,0,0,1]},{"g":[4,4],"db":2,"cars":[[1,3,1,0,2],[3,2,3,1,2],[0,3,1,0,3],[1,2,0,1,2],[2,3,2,0,2],[2,1,0,1,2]],"q":[1,1,1,1,0,1,0,0,1,0,0,0,0]},{"g":[4,4],"db":2,"cars":[[2,3,2,2,2],[3,3,2,1,2],[0,3,2,2,2],[2,1,1,0,2],[1,2,3,1,2],[0,0,0,2,3]],"q":[2,1,2,2,1,1,2,1,2,0,2,2,0]},{"g":[4,4],"db":2,"cars":[[3,1,3,1,3],[2,0,1,0,3],[2,1,1,0,3],[1,1,1,1,2],[0,2,1,1,3],[3,3,2,2,3]],"q":[1,0,1,1,0,0,0,0,0,1,1,1,2,2,1,1,2]},{"g":[4,4],"db":2,"cars":[[2,3,3,2,3],[1,0,0,1,3],[0,1,1,0,2],[3,2,0,1,3],[3,3,3,1,3],[1,1,2,0,2]],"q":[1,1,1,0,1,1,1,0,1,1,1,0,2,0,2,2]},{"g":[4,4],"db":2,"cars":[[0,3,1,1,3],[2,3,2,2,2],[3,0,3,2,3],[0,1,1,2,2],[3,2,3,2,3],[3,3,2,2,2]],"q":[2,2,2,1,1,2,1,2,2,2,2,2,2,2,2]},{"g":[4,4],"db":2,"cars":[[0,0,0,2,3],[3,0,1,0,3],[2,2,3,0,3],[0,2,3,2,2],[0,3,0,0,2],[2,3,2,1,2]],"q":[1,1,0,0,0,2,2,2,0,0,0,0,2,0,2]},{"g":[4,4],"db":2,"cars":[[1,3,0,0,3],[2,1,2,2,2],[3,2,3,0,3],[1,0,3,1,3],[1,2,0,0,3],[2,2,0,0,2]],"q":[0,0,0,0,0,0,0,0,0,1,1,1,2,2,0,0]},{"g":[4,4],"db":2,"cars":[[1,3,0,2,3],[2,1,1,2,3],[2,0,1,2,3],[0,3,0,1,3],[1,2,0,1,3],[0,1,2,0,3]],"q":[2,2,1,2,1,0,1,0,2,0,2,2,2,2,2,1,1,1]},{"g":[4,4],"db":2,"cars":[[3,3,3,2,2],[0,3,1,0,3],[0,0,0,2,3],[1,0,0,1,2],[3,1,0,2,3],[1,2,0,1,3]],"q":[0,0,2,0,2,1,1,1,2,2,2,1,1,2,2,2]},{"g":[4,4],"db":2,"cars":[[3,2,0,2,3],[1,2,1,2,2],[0,1,3,0,2],[1,3,0,2,3],[2,3,1,1,3],[3,1,2,2,3]],"q":[2,2,1,1,2,1,2,2,2,2,0,2,2,0,2,2]},{"g":[4,4],"db":2,"cars":[[1,3,3,0,2],[3,3,0,1,2],[1,1,0,2,3],[2,1,2,0,2],[0,0,1,2,2],[2,0,2,1,3]],"q":[2,0,2,0,1,1,1,2,0,1,0,1,2,2]},{"g":[4,4],"db":2,"cars":[[1,2,1,0,2],[2,1,2,1,2],[0,2,1,1,2],[3,3,0,2,2],[3,1,1,2,2],[3,0,0,2,2]],"q":[1,1,0,2,0,2,2,2,2,2,1,1]},{"g":[4,5],"db":2,"cars":[[1,1,0,3,3],[0,2,1,2,3],[0,0,3,0,3],[2,4,1,1,3],[3,3,3,1,2],[1,3,3,3,2],[2,0,1,0,3],[3,1,0,0,3]],"q":[1,0,1,0,1,2,0,2,2,3,3,3,3,3,0,1,0,0,1,0,0,0]},{"g":[4,5],"db":2,"cars":[[2,3,2,3,2],[1,0,0,1,2],[3,2,1,1,3],[0,3,0,3,2],[1,2,2,0,2],[0,2,0,0,3],[2,1,0,0,3],[1,1,0,1,2]],"q":[1,1,1,3,3,0,0,1,1,3,1,3,1,0,0,0,0,0,0]},{"g":[4,5],"db":2,"cars":[[3,1,1,0,3],[3,0,3,2,3],[2,3,0,0,2],[1,0,0,3,3],[0,2,0,1,2],[0,0,3,2,2],[2,2,3,1,2],[0,4,1,1,2]],"q":[1,0,1,0,2,0,2,2,2,2,3,3,3,0,1,1,0,1,1]},{"g":[4,5],"db":2,"cars":[[3,0,3,3,2],[1,4,1,2,3],[1,3,0,3,2],[0,0,2,0,3],[0,1,0,2,2],[3,2,2,2,3],[1,1,0,2,3],[2,4,3,1,3]],"q":[1,1,2,1,3,3,2,3,3,2,0,0,2,2,0,2,2,2,2,2,2]},{"g":[4,5],"db":2,"cars":[[2,1,3,1,3],[0,0,3,0,3],[2,2,0,0,3],[3,1,2,0,2],[0,3,2,3,3],[2,3,2,1,2],[2,0,3,2,2],[3,3,1,1,3]],"q":[2,2,1,0,0,0,1,1,1,0,1,0,1,0,0,1,0,1,3,3,3]},{"g":[4,5],"db":2,"cars":[[3,2,2,2,3],[1,1,1,0,2],[3,1,2,2,2],[2,4,1,1,3],[0,4,1,1,3],[0,0,1,1,2],[2,1,3,1,2],[2,2,1,0,2]],"q":[2,1,2,1,0,0,1,1,1,2,1,1,2,2,1,1,1,0,0]},{"g":[4,5],"db":2,"cars":[[0,4,1,2,3],[2,2,3,2,2],[2,3,0,0,2],[3,0,1,0,3],[2,4,2,0,3],[0,1,2,1,3],[2,0,0,0,2],[0,3,3,3,3]],"q":[1,1,1,2,2,2,0,0,0,0,3,0,3,3,0,0,0,2,2,0,0]},{"g":[4,5],"db":2,"cars":[[2,0,0,1,3],[3,4,3,2,2],[3,2,3,1,2],[2,2,3,0,2],[2,3,0,2,3],[0,1,3,1,2],[1,3,0,0,3],[1,1,2,0,2]],"q":[1,1,1,2,2,1,0,0,0,0,0,1,1,1,0,0,2,2,2]},{"g":[4,5],"db":2,"cars":[[0,1,0,3,2],[2,1,0,3,3],[1,1,3,3,3],[1,3,1,2,3],[1,2,3,3,2],[0,2,3,2,3],[3,1,0,0,2],[2,4,1,0,3]],"q":[2,0,2,0,2,0,3,3,3,3,3,3,3,3,0,0,3,3,2,2,2]},{"g":[4,5],"db":2,"cars":[[3,3,3,2,3],[0,1,0,2,3],[2,2,2,1,2],[0,3,2,2,3],[3,2,2,0,2],[2,4,3,1,2],[1,4,3,0,2],[2,0,3,0,3]],"q":[0,0,0,2,2,2,0,0,0,0,1,1,1,1,2,2,2,2,2,2]},{"g":[4,5],"db":2,"cars":[[0,1,3,0,3],[3,4,2,1,3],[1,3,1,3,3],[2,0,1,2,3],[0,3,3,2,2],[0,0,3,2,3],[3,3,3,1,2],[0,2,2,0,2]],"q":[1,1,1,2,2,2,2,2,2,0,0,3,0,3,3,1,0,0,1,2,2]},{"g":[4,5],"db":2,"cars":[[3,3,0,1,3],[1,2,0,0,2],[3,2,1,0,2],[2,4,1,2,2],[0,1,1,1,3],[2,2,0,1,2],[3,4,2,3,3],[1,1,1,2,3]],"q":[3,3,1,1,1,3,0,0,1,1,2,2,0,1,0,2,2,2,1,1]},{"g":[4,5],"db":2,"cars":[[1,0,1,0,2],[3,3,1,0,2],[1,4,0,0,2],[0,4,1,1,3],[0,0,1,0,3],[0,1,0,2,3],[3,4,2,0,2],[1,2,2,3,2]],"q":[1,1,1,2,3,3,2,2,0,0,0,0,0,0,0,0,0,0,0]},{"g":[4,5],"db":2,"cars":[[0,3,1,0,2],[2,4,2,2,3],[2,2,0,3,3],[3,3,1,1,2],[2,3,3,2,3],[1,1,3,0,2],[0,1,1,2,3],[3,1,3,2,2]],"q":[2,2,2,0,0,0,1,0,1,3,2,3,2,2,3,2,2,2,2,2]},{"g":[4,5],"db":2,"cars":[[2,2,0,1,2],[0,2,0,3,2],[2,0,3,1,3],[1,1,1,3,3],[3,1,1,0,2],[1,2,1,2,2],[3,4,2,0,3],[3,0,1,2,2]],"q":[3,3,0,0,0,0,0,3,2,3,2,2,3,1,2,1,1,1,1]},{"g":[5,5],"db":3,"cars":[[4,4,3,2,2],[3,3,0,0,2],[0,2,0,4,3],[3,1,0,4,2],[2,4,0,2,3],[0,4,1,3,3],[1,2,0,2,3],[4,0,0,4,3],[0,3,3,4,2],[2,2,2,1,3]],"q":[4,4,4,3,2,2,4,4,3,1,3,1,1,4,2,2,4,2,2,2,2,4,4,4,0,0]},{"g":[5,5],"db":3,"cars":[[3,3,1,2,2],[4,0,0,0,2],[4,4,1,1,3],[1,4,1,0,2],[1,1,3,1,2],[4,1,2,0,2],[2,3,2,1,2],[3,2,2,2,2],[2,2,3,2,3],[0,1,2,0,3]],"q":[2,1,1,2,1,2,0,1,0,0,1,0,0,0,2,2,2,0,2,0,0,1,1]},{"g":[5,5],"db":3,"cars":[[4,4,3,3,3],[2,1,2,3,2],[2,2,1,1,3],[0,3,3,0,2],[3,4,2,4,2],[0,4,2,2,2],[3,2,0,0,3],[3,0,3,1,3],[2,3,2,0,3],[1,1,2,2,2]],"q":[3,3,3,3,3,1,1,0,4,1,2,2,0,4,0,0,1,0,1,1,0,0,0,2,2]},{"g":[5,5],"db":3,"cars":[[3,4,3,3,2],[3,3,3,0,3],[4,0,3,1,2],[4,3,2,1,2],[1,3,0,3,2],[1,1,3,0,3],[1,4,2,1,3],[1,0,3,4,3],[0,3,3,3,3],[0,4,3,2,2]],"q":[1,4,3,4,3,3,4,1,1,1,0,2,2,0,0,3,0,3,3,1,1,1,0,0,3]},{"g":[5,5],"db":3,"cars":[[4,2,0,3,2],[3,1,3,4,3],[3,2,0,2,2],[4,1,2,3,2],[0,4,3,1,3],[2,0,1,3,2],[2,1,2,1,3],[2,3,1,2,2],[4,3,1,4,2],[3,3,2,3,3]],"q":[2,2,4,4,3,3,3,3,1,1,1,4,3,4,2,4,2,3,3,3,3,1,1,1]},{"g":[5,5],"db":3,"cars":[[4,1,2,3,3],[1,4,3,3,2],[3,1,0,2,3],[0,1,0,3,2],[2,3,1,0,3],[3,2,2,3,2],[1,2,0,0,3],[2,0,3,0,3],[0,4,1,2,3],[1,3,0,0,3]],"q":[0,0,0,0,0,2,3,3,0,2,2,0,0,0,3,3,3,3,3,3,2,0,0,3,2,0,2]},{"g":[5,5],"db":3,"cars":[[3,3,2,4,2],[1,4,1,1,2],[0,1,0,0,3],[4,4,0,1,2],[2,1,2,2,3],[3,4,0,4,3],[4,2,1,3,2],[2,3,1,1,2],[4,1,1,3,3],[1,3,0,3,3]],"q":[1,1,0,3,3,0,0,4,3,4,4,1,4,4,1,1,1,3,3,3,2,2,2,3,3]},{"g":[5,5],"db":3,"cars":[[2,2,3,1,3],[4,3,0,1,2],[1,1,2,4,3],[0,4,1,3,3],[1,3,0,1,2],[2,1,2,4,3],[0,2,0,4,2],[2,3,1,0,2],[2,0,3,1,3],[3,2,3,3,2]],"q":[3,1,3,1,3,1,1,1,0,0,4,1,1,1,4,4,3,3,4,1,4,4,1,4,4]},{"g":[5,5],"db":3,"cars":[[2,0,0,3,3],[3,4,3,2,3],[1,2,0,4,3],[2,1,2,4,3],[1,4,0,3,2],[0,4,0,2,3],[2,2,0,0,2],[0,0,0,1,2],[0,1,0,3,3],[0,2,3,1,2]],"q":[1,3,3,1,3,3,3,2,3,2,2,1,2,3,3,2,2,1,4,4,4,4,4,0,0,4]},{"g":[5,5],"db":3,"cars":[[3,3,3,0,2],[4,4,3,4,3],[4,3,0,4,2],[3,2,3,0,2],[1,0,3,4,2],[1,1,2,2,3],[2,2,3,1,2],[1,3,1,0,2],[0,4,1,1,3],[1,2,2,0,2]],"q":[4,4,2,1,0,2,1,0,2,0,0,1,0,1,0,1,0,4,0,4,4,4,4]},{"g":[5,5],"db":3,"cars":[[3,4,3,1,3],[3,2,3,3,2],[2,2,1,0,3],[4,4,0,1,2],[1,3,1,4,2],[1,0,0,1,3],[4,0,0,2,2],[4,3,2,2,2],[1,2,0,0,3],[2,1,0,0,3]],"q":[3,3,2,2,4,4,0,0,0,1,0,0,1,1,1,1,0,2,2,1,1,1,0,0,0]},{"g":[5,5],"db":3,"cars":[[4,1,2,2,2],[4,0,2,3,2],[0,1,0,0,3],[0,0,1,0,2],[3,0,3,3,3],[2,0,3,4,3],[3,4,1,4,2],[0,2,1,0,3],[3,2,1,4,2],[1,4,3,4,3]],"q":[2,2,4,0,0,3,0,4,4,0,3,4,4,4,0,4,0,0,4,4,4,0,3,3,3]},{"g":[5,5],"db":3,"cars":[[4,0,3,2,2],[1,4,2,4,3],[3,3,3,1,3],[2,2,0,2,2],[1,1,0,4,2],[0,2,3,0,2],[2,0,2,2,3],[0,0,0,2,2],[0,3,2,1,2],[0,1,0,0,3]],"q":[2,2,2,0,0,0,2,1,4,4,2,4,2,2,0,0,1,1,1,1,4,2,2,4]},{"g":[5,5],"db":3,"cars":[[1,2,1,3,2],[3,0,3,0,3],[0,0,3,1,3],[0,2,3,2,2],[4,3,1,2,2],[2,0,2,4,3],[0,4,2,4,3],[3,2,2,2,3],[3,1,3,2,3],[3,3,1,3,3]],"q":[3,2,2,2,2,3,0,4,2,4,3,4,2,2,2,3,0,0,4,3,4,4,1,1,1,2,2]},{"g":[5,5],"db":3,"cars":[[4,0,2,0,3],[2,2,0,4,2],[4,3,2,1,3],[2,4,3,0,3],[1,3,1,3,3],[0,4,2,2,2],[4,4,3,0,3],[3,1,1,0,2],[1,0,1,4,3],[2,3,3,0,3]],"q":[1,0,1,0,0,1,0,0,3,0,4,0,0,3,4,3,0,0,0,2,4,0,2,0,4,4,0]},{"g":[5,6],"db":3,"cars":[[1,0,3,1,2],[2,4,0,3,4],[1,1,3,0,3],[1,4,0,3,3],[4,1,0,1,4],[3,5,0,0,3],[0,0,0,1,2],[2,1,3,5,2],[2,5,0,0,3],[1,3,3,0,4],[4,2,2,0,3],[2,2,1,0,4]],"q":[3,5,3,5,0,3,1,0,3,1,0,3,1,1,0,0,3,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0]},{"g":[5,6],"db":3,"cars":[[2,5,0,4,2],[2,2,2,5,2],[4,5,1,0,2],[2,3,0,5,3],[3,5,1,3,4],[3,3,1,2,2],[2,1,2,3,2],[1,5,3,4,2],[3,4,0,5,3],[0,1,0,5,3],[3,0,2,2,3],[0,4,0,3,2]],"q":[3,5,5,5,5,3,3,5,5,3,3,3,4,4,3,5,0,3,4,5,4,2,5,2,0,5,5,2,2,2]},{"g":[5,6],"db":3,"cars":[[2,4,0,1,2],[1,0,2,3,3],[4,0,2,5,4],[2,5,2,4,2],[3,4,2,3,2],[3,0,1,1,2],[1,1,0,4,3],[4,2,2,1,3],[1,4,3,4,3],[4,1,1,0,2],[0,0,3,0,3],[2,1,1,1,4]],"q":[3,5,5,5,3,1,1,5,1,0,0,1,1,4,3,4,4,3,3,4,1,1,4,0,4,1,1,0,1,1,4,4,0]},{"g":[5,6],"db":3,"cars":[[1,0,3,2,2],[2,4,2,0,4],[1,5,3,4,3],[4,1,1,0,4],[3,5,0,1,2],[2,1,0,2,4],[3,2,2,1,3],[4,4,2,4,4],[2,3,0,3,4],[2,0,1,1,4],[3,4,2,4,3],[3,0,0,1,2]],"q":[2,2,2,2,4,3,3,4,3,3,1,1,4,1,4,2,2,4,4,4,4,0,1,4,4,1,0,1,0,1,0,1,1,1,0,1,0,0,0]},{"g":[5,6],"db":3,"cars":[[2,4,0,3,3],[4,5,2,0,3],[1,1,1,4,2],[1,2,1,4,2],[4,2,1,4,2],[2,2,3,5,3],[3,1,1,0,2],[0,3,2,4,3],[3,4,1,5,3],[4,0,1,2,2],[2,0,3,0,4],[1,5,2,3,2]],"q":[5,0,5,0,4,5,4,0,4,4,4,0,3,3,3,3,3,4,0,0,4,5,0,4,0,5,5,2,0,4,2]},{"g":[5,6],"db":3,"cars":[[4,3,2,2,4],[3,4,3,0,4],[3,3,2,3,2],[4,2,2,4,2],[2,5,1,2,3],[4,4,0,0,2],[1,0,0,5,4],[1,4,3,4,4],[2,3,1,1,2],[2,4,0,1,2],[4,0,0,4,2],[1,3,3,3,3]],"q":[2,2,4,4,2,5,5,5,5,3,4,2,2,4,4,3,4,3,1,1,3,3,4,1,4,0,0,0,1,2,2,0,0,0]},{"g":[5,6],"db":3,"cars":[[3,4,1,1,3],[0,2,2,0,2],[4,5,2,3,2],[3,2,1,3,3],[4,2,1,0,2],[2,4,1,0,3],[1,1,2,4,2],[4,4,1,4,4],[2,0,1,1,3],[3,1,2,0,4],[4,3,0,3,3],[0,5,1,1,3]],"q":[3,3,1,1,0,1,3,3,3,0,0,4,4,0,4,1,0,1,0,0,4,1,1,1,4,3,4,3,1,0,3,0,0,0]},{"g":[5,6],"db":3,"cars":[[3,0,0,5,3],[2,0,1,5,4],[1,3,2,4,3],[1,4,0,3,4],[0,0,1,0,3],[2,1,1,1,2],[1,2,3,4,4],[1,1,3,0,3],[1,5,2,3,2],[1,0,0,0,4],[3,3,1,3,3],[4,0,0,1,4]],"q":[3,3,3,3,3,3,3,3,0,4,0,4,4,3,0,0,0,0,0,5,0,1,5,0,1,5,0,5,4,5,4,5,5,4,1,4,1,1,1]},{"g":[5,6],"db":3,"cars":[[4,3,2,1,2],[3,4,1,2,3],[2,2,2,4,2],[4,0,2,3,4],[0,3,0,1,4],[2,1,3,2,3],[1,2,1,1,3],[1,3,1,1,4],[4,2,1,2,3],[3,0,1,4,2],[3,5,2,3,2],[1,1,2,2,2]],"q":[1,3,3,1,1,2,3,2,1,1,1,3,2,2,1,1,1,3,3,2,2,2,2,1,2,4,4,1,2,1,1,4,4,2]},{"g":[5,6],"db":3,"cars":[[0,0,0,5,3],[0,3,1,5,2],[4,5,3,2,4],[2,3,3,4,3],[1,1,0,1,3],[3,3,3,2,2],[4,4,0,0,3],[2,2,0,2,2],[2,4,1,4,4],[2,0,0,0,4],[3,0,3,5,2],[2,5,0,4,3]],"q":[5,2,5,5,2,4,5,5,5,5,4,2,4,2,4,4,4,4,4,0,1,0,0,4,1,4,1,0,0,0,2,2,0,2,2]},{"g":[5,6],"db":3,"cars":[[3,3,3,5,2],[2,5,0,4,3],[1,4,0,0,4],[4,2,3,4,2],[1,3,0,0,3],[2,0,0,0,3],[4,4,0,0,4],[0,2,3,0,2],[1,1,2,2,4],[3,1,2,1,4],[1,0,0,1,4],[4,0,2,0,3]],"q":[0,0,1,0,1,0,0,0,0,0,0,1,1,2,1,1,2,2,1,4,4,1,0,2,4,4,4,0,0,0,0,0,5,0,5,0,0,0]},{"g":[5,6],"db":3,"cars":[[4,2,2,5,4],[3,5,0,1,4],[4,0,3,1,3],[2,0,2,0,4],[4,5,3,5,4],[1,1,1,0,3],[0,3,3,0,2],[4,4,0,0,3],[2,2,2,2,3],[0,2,0,2,3],[0,1,0,5,2],[2,1,3,4,3]],"q":[1,1,1,5,5,0,5,5,5,5,0,2,0,0,0,2,0,2,0,0,0,0,4,0,4,4,2,5,5,5,0,2,5,1,1,2,1,1]},{"g":[5,6],"db":3,"cars":[[3,0,3,5,4],[2,4,3,5,3],[2,3,2,1,4],[1,3,0,2,4],[3,4,1,3,4],[1,1,3,4,3],[2,2,0,2,2],[3,2,3,3,2],[3,3,2,2,2],[4,5,3,2,4],[4,2,3,0,4],[0,2,1,1,2]],"q":[4,4,4,2,2,1,1,1,1,2,2,1,1,5,5,0,5,0,3,5,5,3,0,0,5,5,2,2,2,2,2,2,3,2,3,3,3,2]},{"g":[5,6],"db":3,"cars":[[0,2,0,4,4],[2,2,1,5,2],[3,0,0,4,3],[1,0,3,2,2],[0,4,3,4,4],[4,2,1,2,2],[4,1,1,0,3],[1,5,1,5,2],[4,0,3,3,2],[0,3,2,2,4],[4,3,1,3,4],[0,5,3,3,4]],"q":[5,4,5,5,2,4,4,2,5,4,3,2,3,3,2,3,2,2,4,3,4,4,4,4,4,3,2,4,2,0,0,3,0,3,3,3]},{"g":[5,6],"db":3,"cars":[[2,5,2,0,2],[3,2,1,3,3],[2,4,0,3,4],[0,2,3,3,3],[4,5,2,4,3],[2,1,3,2,3],[4,1,0,5,4],[1,5,2,2,2],[0,3,2,2,2],[4,4,1,4,2],[3,5,2,4,4],[1,1,3,2,3]],"q":[3,3,3,3,3,3,3,4,4,2,4,4,2,4,2,2,5,5,2,5,5,4,4,2,2,0,2,4,3,3,3,4,0,2,2]},{"g":[6,6],"db":4,"cars":[[0,4,3,1,4],[3,1,1,2,3],[4,4,3,6,4],[2,1,3,1,3],[1,3,2,4,4],[5,3,2,2,3],[0,3,0,4,3],[5,0,3,0,4],[3,4,2,2,4],[5,2,3,4,2],[3,0,3,1,2],[2,3,2,1,2],[1,2,1,5,3],[1,1,1,6,4]],"q":[6,0,6,1,1,6,2,2,6,1,1,4,1,4,0,2,0,0,4,4,2,1,4,2,1,4,1,1,1,4,2,2,2,4,1,5,2,6,4,2,5,6,6,5,6]},{"g":[6,6],"db":4,"cars":[[5,5,0,2,3],[2,2,3,0,2],[2,5,3,5,3],[4,4,1,2,2],[0,4,3,4,2],[5,2,1,1,4],[1,5,0,2,2],[4,1,2,3,2],[0,3,2,3,3],[4,2,0,5,2],[5,0,1,5,4],[3,1,3,3,4],[4,0,1,2,4],[0,5,1,0,2]],"q":[3,3,3,2,2,0,0,4,3,3,5,5,3,5,4,0,3,0,2,3,2,3,2,2,5,2,5,5,5,1,5,1,1,5,2,1,2,2,2]},{"g":[6,6],"db":4,"cars":[[3,2,0,5,3],[0,2,0,0,3],[1,1,3,2,3],[3,0,3,3,2],[1,4,0,0,4],[3,5,2,5,2],[1,5,1,0,4],[3,1,1,0,2],[5,3,2,6,4],[4,2,0,0,2],[5,4,0,2,2],[0,3,3,5,4],[2,3,0,0,3],[4,5,2,6,2]],"q":[3,6,6,3,6,6,6,2,0,2,6,0,2,2,0,0,0,5,0,0,0,5,2,5,0,5,0,5,5,0,0,5,5,5,0,0,0,0,0,0]},{"g":[6,6],"db":4,"cars":[[4,1,1,1,4],[3,0,1,0,3],[2,0,2,1,4],[3,4,2,1,3],[3,3,2,3,2],[1,3,1,2,4],[3,5,1,1,3],[1,1,2,2,2],[0,3,0,1,2],[5,0,2,6,2],[0,5,0,2,4],[3,1,2,4,3],[1,0,3,5,2],[2,1,2,4,4]],"q":[1,1,6,6,1,2,2,2,1,1,2,1,5,2,1,1,1,2,2,5,1,1,4,2,1,4,3,3,0,0,4,0,1,2,1,1,1,4,2,4,4,4]},{"g":[6,6],"db":4,"cars":[[4,5,1,3,2],[0,0,2,0,2],[1,0,3,0,3],[0,3,2,2,4],[3,4,1,3,4],[0,4,1,0,4],[2,3,1,0,4],[2,1,3,1,4],[2,0,3,3,3],[1,5,1,4,2],[5,5,0,0,2],[3,2,2,6,4],[0,2,3,0,4],[5,3,2,4,2]],"q":[3,0,3,0,0,4,0,0,4,4,0,4,0,0,0,0,0,6,3,3,3,2,6,6,2,6,2,3,3,2,1,0,0,1,1,1,3,3,0,0,0,0,0,0]}];
const PL_LEVEL_COUNT = PL_LEVELS.length;

function plGenerateLevel(levelIndex) {
  const level = PL_LEVELS[levelIndex];
  const cars = level.cars.map(([r, c, dir, ci, seats]) => ({ r, c, dir, color: PL_COLORS[ci], seats }));
  const queue = level.q.map(ci => PL_COLORS[ci]);
  const maxBays = new Set(cars.map(c => c.color)).size;
  return { cars, queue, maxBays, db: level.db, grid: level.g };
}

/* ══════════════════════════════════════════════════════════
   CORE SOLVER — pure functions, no DOM/globals, reused verbatim by
   scripts/generate-parking-levels.js and scripts/verify-parking-levels.js
   via the module.exports guard at the bottom of this file.
══════════════════════════════════════════════════════════ */
function plIsBlocked(cars, parkedMask, idx) {
  const car = cars[idx];
  for (let j = 0; j < cars.length; j++) {
    if (j === idx || !(parkedMask & (1 << j))) continue;
    const o = cars[j];
    if (car.dir === 0 && o.c === car.c && o.r < car.r) return true;
    if (car.dir === 1 && o.r === car.r && o.c > car.c) return true;
    if (car.dir === 2 && o.c === car.c && o.r > car.r) return true;
    if (car.dir === 3 && o.r === car.r && o.c < car.c) return true;
  }
  return false;
}
function plFirstEmptyBaySlot(bayCar, bayLimit) {
  for (let i = 0; i < bayLimit; i++) if (bayCar[i] == null) return i;
  return -1;
}
function plLowestOpenSlotForColor(cars, bayCar, bayFilled, color) {
  for (let i = 0; i < bayCar.length; i++) {
    if (bayCar[i] == null) continue;
    const car = cars[bayCar[i]];
    if (car.color === color && bayFilled[i] < car.seats) return i;
  }
  return -1;
}
function plCanRelease(cars, parkedMask, bayCar, bayLimit, idx) {
  return !!(parkedMask & (1 << idx))
    && !plIsBlocked(cars, parkedMask, idx)
    && plFirstEmptyBaySlot(bayCar, bayLimit) !== -1;
}
// Deterministic, no choices — repeatedly board the front-of-queue passenger
// into the LOWEST-INDEX open matching bay slot; stop the instant the front
// passenger has no match (strict front-of-queue, never skips ahead).
function plAutoResolve(cars, queue, queuePos, bayCar, bayFilled) {
  let pos = queuePos;
  const outCar = bayCar.slice(), outFilled = bayFilled.slice();
  while (pos < queue.length) {
    const slot = plLowestOpenSlotForColor(cars, outCar, outFilled, queue[pos]);
    if (slot === -1) break;
    outFilled[slot]++;
    pos++;
    if (outFilled[slot] === cars[outCar[slot]].seats) { outCar[slot] = null; outFilled[slot] = 0; }
  }
  return { queuePos: pos, bayCar: outCar, bayFilled: outFilled };
}
// The only player-facing transition.
function plReleaseCar(cars, queue, state, bayLimit, idx) {
  if (!plCanRelease(cars, state.parkedMask, state.bayCar, bayLimit, idx)) return null;
  const slot = plFirstEmptyBaySlot(state.bayCar, bayLimit);
  const bayCar = state.bayCar.slice(); bayCar[slot] = idx;
  const bayFilled = state.bayFilled.slice(); bayFilled[slot] = 0;
  const parkedMask = state.parkedMask & ~(1 << idx);
  const resolved = plAutoResolve(cars, queue, state.queuePos, bayCar, bayFilled);
  return { parkedMask, bayCar: resolved.bayCar, bayFilled: resolved.bayFilled, queuePos: resolved.queuePos };
}
function plIsWon(state) { return state.parkedMask === 0 && state.bayCar.every(c => c === null); }
function plIsDeadlocked(cars, state, bayLimit) {
  if (state.parkedMask === 0) return false;
  for (let i = 0; i < cars.length; i++)
    if ((state.parkedMask & (1 << i)) && plCanRelease(cars, state.parkedMask, state.bayCar, bayLimit, i)) return false;
  return true;
}
// DFS + memoized dead-state set. mode 'exists' stops at the first solution;
// mode 'count' keeps searching (capped) to grade difficulty by how many
// distinct valid orders exist. `budget` caps states visited, so a pathological
// level fails generation loudly instead of hanging the generator.
function plSolve(cars, queue, bayLimit, maxBays, mode, cap, budget) {
  const dead = new Set();
  let solutionCount = 0;
  let visited = 0;
  let aborted = false;
  const start = {
    parkedMask: cars.length === 32 ? -1 >>> 0 : (1 << cars.length) - 1,
    bayCar: Array(maxBays).fill(null),
    bayFilled: Array(maxBays).fill(0),
    queuePos: 0,
  };
  const key = s => s.parkedMask + '|' + s.bayCar.join(',') + '|' + s.bayFilled.join(',') + '|' + s.queuePos;
  function dfs(state) {
    if (plIsWon(state)) { solutionCount++; return true; }
    if (budget && ++visited > budget) { aborted = true; return false; }
    const k = key(state);
    if (dead.has(k)) return false;
    let any = false;
    for (let i = 0; i < cars.length && !aborted; i++) {
      if (!plCanRelease(cars, state.parkedMask, state.bayCar, bayLimit, i)) continue;
      const found = dfs(plReleaseCar(cars, queue, state, bayLimit, i));
      any = any || found;
      if (mode === 'exists' && found) return true;
      if (mode === 'count' && solutionCount >= cap) return true;
    }
    if (!any && !aborted) dead.add(k);
    return any;
  }
  const solvable = dfs(start);
  return { solvable, solutionCount, aborted };
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.parkingLot
══════════════════════════════════════════════════════════ */
// Transient, purely-visual state for plRender() — never persisted in G.
let plAnimating = false;   // input lock during the departure/boarding defer window
let plPrevBayState = null; // { bayCar, bayFilled } snapshot from just before the last commit, for the "seat just filled" pop

function plOnCarTap(carIdx) {
  if (plAnimating) return;
  const pl = G.parkingLot;
  const level = plGenerateLevel(pl.currentLevelIndex);
  if (!(pl.parkedMask & (1 << carIdx))) return; // already released
  if (plIsBlocked(level.cars, pl.parkedMask, carIdx)) { showToast("🚫 Blockiert!"); return; }
  if (plFirstEmptyBaySlot(pl.bayCar, pl.bayUnlocked) === -1) { showToast("🅿️ Keine freie Ladebucht!"); return; }
  const next = plReleaseCar(level.cars, level.queue,
    { parkedMask: pl.parkedMask, bayCar: pl.bayCar, bayFilled: pl.bayFilled, queuePos: pl.queuePos },
    pl.bayUnlocked, carIdx);
  if (!next) return;

  const boardedCount = next.queuePos - pl.queuePos; // passengers this release also boards, via plAutoResolve
  plAnimating = true;
  plPlayDepartureAnimation(carIdx, level.cars[carIdx], boardedCount, () => {
    plAnimating = false;
    plPrevBayState = { bayCar: pl.bayCar.slice(), bayFilled: pl.bayFilled.slice() };
    Object.assign(pl, next);
    saveState(); // explicit — mid-level progress must survive a reload
    if (plIsWon(next)) { plOnLevelSolved(); return; }
    if (plIsDeadlocked(level.cars, next, pl.bayUnlocked)) showToast("🚧 Feststeckt — versuch's mit 🔄 Neu starten!");
    plRender();
  });
}

// Animates the currently-mounted car cell driving off in its exit direction
// and the front-of-queue passenger dot(s) about to board hopping toward the
// bay row — then calls onDone. This can't be done via CSS-on-insert (the
// technique used elsewhere for "arriving" things) since these elements are
// about to be REMOVED by the next full render, not inserted; the current
// DOM nodes have to be animated directly before that render happens.
const PL_DIR_VECTOR = [[0, -1], [1, 0], [0, 1], [-1, 0]]; // 0=up,1=right,2=down,3=left, as [dx,dy]
function plPlayDepartureAnimation(carIdx, car, boardedCount, onDone) {
  const carEl = document.querySelector(`#pl-lot-grid [data-idx="${carIdx}"]`);
  const queueEls = document.querySelectorAll('#pl-queue-strip .pl-queue-item');
  const boardingEls = Array.from(queueEls).slice(0, boardedCount);

  if (!carEl && !boardingEls.length) { onDone(); return; } // defensive — never block the game on a missing element

  const [dx, dy] = PL_DIR_VECTOR[car.dir];
  requestAnimationFrame(() => {
    if (carEl) {
      carEl.style.transition = 'transform 0.32s ease-in, opacity 0.32s ease-in';
      carEl.style.transform = `translate(${dx * 140}%, ${dy * 140}%)`;
      carEl.style.opacity = '0';
    }
    boardingEls.forEach((el, i) => {
      el.style.transition = `transform 0.3s ease-in ${i * 40}ms, opacity 0.3s ease-in ${i * 40}ms`;
      el.style.transform = 'translateY(24px) scale(0.4)';
      el.style.opacity = '0';
    });
  });
  setTimeout(onDone, 360);
}

function plOnLevelSolved() {
  G.stats.parkingLevelsCompleted = (G.stats.parkingLevelsCompleted || 0) + 1;
  checkTrophies();
  showToast("🚗 Alle eingestiegen!");
  saveState();
  plRender();
  setTimeout(plAdvanceToNextLevel, 900);
}

function plAdvanceToNextLevel() {
  const pl = G.parkingLot;
  pl.playOrderPos++;
  if (pl.playOrderPos >= pl.playOrder.length) {
    const prevLast = pl.playOrder[pl.playOrder.length - 1];
    const order = shuffleArray([...Array(PL_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    pl.playOrder = order;
    pl.playOrderPos = 0;
  }
  plStartLevel(pl.playOrder[pl.playOrderPos]);
}

function plStartLevel(levelIndex) {
  const pl = G.parkingLot;
  const level = plGenerateLevel(levelIndex);
  pl.currentLevelIndex = levelIndex;
  pl.parkedMask = level.cars.length === 32 ? -1 >>> 0 : (1 << level.cars.length) - 1;
  pl.bayCar = Array(level.maxBays).fill(null);
  pl.bayFilled = Array(level.maxBays).fill(0);
  pl.queuePos = 0;
  pl.bayUnlocked = level.db;
  plAnimating = false;
  plPrevBayState = null;
  saveState();
  plRender();
}

function plRestartLevel() {
  const pl = G.parkingLot;
  if (pl.currentLevelIndex == null) return;
  plStartLevel(pl.currentLevelIndex);
  showToast("🔄 Level neu gestartet.");
}

function plEnsureQueueAndLevel() {
  const pl = G.parkingLot;
  if (!pl.playOrder.length) {
    pl.playOrder = shuffleArray([...Array(PL_LEVEL_COUNT).keys()]);
    pl.playOrderPos = 0;
  }
  if (pl.currentLevelIndex == null || !pl.bayCar.length) {
    plStartLevel(pl.playOrder[pl.playOrderPos]);
  } else {
    plRender();
  }
}

function plBuyExtraBay() {
  const pl = G.parkingLot;
  const level = plGenerateLevel(pl.currentLevelIndex);
  if (pl.bayUnlocked >= level.maxBays) {
    showToast(`Maximal ${level.maxBays} Ladebuchten für dieses Level!`);
    return;
  }
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🚗 Zusatzladebucht", 1, () => {
    pl.bayUnlocked++;
    G.stats.parkingBaysUnlockedTotal = (G.stats.parkingBaysUnlockedTotal || 0) + 1;
    checkTrophies();
    saveState();
    if (!plIsDeadlocked(level.cars, pl, pl.bayUnlocked)) { /* no-op, just re-render below */ }
    plRender();
    showToast("🚗 Neue Ladebucht freigeschaltet!");
  }, null);
}

/* ══════════════════════════════════════════════════════════
   RENDERING — full innerHTML rebuild + re-bind onclick each call, per this
   app's established convention (no incremental DOM diffing anywhere).
══════════════════════════════════════════════════════════ */
function plRender() {
  const pl = G.parkingLot;
  if (pl.currentLevelIndex == null) return;
  const level = plGenerateLevel(pl.currentLevelIndex);
  const infoEl = document.getElementById("pl-level-info");
  const queueEl = document.getElementById("pl-queue-strip");
  const bayEl = document.getElementById("pl-bay-row");
  const lotEl = document.getElementById("pl-lot-grid");
  const buyBtn = document.getElementById("pl-buy-bay-btn");
  if (!queueEl || !bayEl || !lotEl) return;

  if (infoEl) infoEl.textContent = `Level ${pl.currentLevelIndex + 1} / ${PL_LEVEL_COUNT}`;

  queueEl.innerHTML = level.queue.slice(pl.queuePos).map((color, i) =>
    `<div class="pl-queue-item${i === 0 ? ' pl-queue-item--front' : ''}" style="background:${color};"></div>`
  ).join("");

  const prevBay = plPrevBayState;
  plPrevBayState = null; // consume — a later, unrelated render must not replay it
  bayEl.innerHTML = Array.from({ length: level.maxBays }, (_, i) => {
    if (i >= pl.bayUnlocked) return `<div class="pl-bay-slot pl-bay-slot--locked"></div>`;
    const carIdx = pl.bayCar[i];
    if (carIdx == null) return `<div class="pl-bay-slot pl-bay-slot--empty"></div>`;
    const car = level.cars[carIdx];
    // "new" seats since the last commit: if this slot's occupant just
    // changed (a car freshly released in), every filled seat is new;
    // otherwise only the seats added since the previous snapshot are.
    const sameOccupant = prevBay && prevBay.bayCar[i] === carIdx;
    const newFrom = sameOccupant ? prevBay.bayFilled[i] : 0;
    const dots = Array.from({ length: car.seats }, (_, s) => {
      const filled = s < pl.bayFilled[i];
      const isNew = filled && prevBay && s >= newFrom;
      return `<span class="pl-bay-seat${filled ? ' pl-bay-seat--filled' : ''}${isNew ? ' pl-bay-seat--incoming' : ''}"${isNew ? ` style="animation-delay:${(s - newFrom) * 60}ms"` : ''}></span>`;
    }).join("");
    return `<div class="pl-bay-slot pl-bay-slot--filled" style="background:${car.color};">${dots}</div>`;
  }).join("");

  const [rows, cols] = level.grid;
  lotEl.style.cssText = `grid-template-columns:repeat(${cols},1fr);grid-template-rows:repeat(${rows},1fr);`;
  const carAt = new Map(level.cars.map((car, idx) => [car.r + ',' + car.c, idx]));
  const cellsHtml = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const idx = carAt.get(r + ',' + c);
      if (idx == null) { cellsHtml.push(`<div class="pl-lot-cell pl-lot-cell--floor"></div>`); continue; }
      if (!(pl.parkedMask & (1 << idx))) { cellsHtml.push(`<div class="pl-lot-cell pl-lot-cell--floor"></div>`); continue; }
      const car = level.cars[idx];
      const blocked = plIsBlocked(level.cars, pl.parkedMask, idx);
      const cls = "pl-lot-cell pl-lot-cell--car" + (blocked ? " pl-lot-cell--blocked" : "");
      cellsHtml.push(`<div class="${cls}" style="background:${car.color};" data-idx="${idx}">${PL_DIR_GLYPH[car.dir]}</div>`);
    }
  }
  lotEl.innerHTML = cellsHtml.join("");
  lotEl.querySelectorAll(".pl-lot-cell--car").forEach(el => {
    el.onclick = () => plOnCarTap(parseInt(el.dataset.idx, 10));
  });

  if (buyBtn) {
    const atCap = pl.bayUnlocked >= level.maxBays;
    buyBtn.disabled = atCap;
    buyBtn.classList.toggle("ws-buy-bottle-btn--off", atCap);
    buyBtn.textContent = atCap
      ? "➕ Maximal erreicht"
      : `➕ Ladebucht (1 Frage) · ${pl.bayUnlocked}/${level.maxBays}`;
  }
}

if (typeof window !== 'undefined') {
  window.plOnCarTap = plOnCarTap;
  window.plRestartLevel = plRestartLevel;
  window.plEnsureQueueAndLevel = plEnsureQueueAndLevel;
  window.plBuyExtraBay = plBuyExtraBay;
  window.plRender = plRender;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    PL_COLORS, PL_LEVELS, PL_LEVEL_COUNT, plGenerateLevel,
    plIsBlocked, plFirstEmptyBaySlot, plLowestOpenSlotForColor, plCanRelease,
    plAutoResolve, plReleaseCar, plIsWon, plIsDeadlocked, plSolve,
  };
}
