'use strict';

/* ══════════════════════════════════════════════════════════
   PARKPLATZ — Rush Hour sliding-car puzzle

   A grid of cars/trucks (2 or 3 cells, fixed horizontal/vertical
   orientation, no rotating) sits on a grid; slide vehicles along their own
   axis, as far as unobstructed cells allow, to clear a path for the target
   vehicle (index 0 in every level, always horizontal length 2) to reach the
   exit on the grid's right edge.

   Sliding moves are naturally, perfectly reversible — a slide from cell A
   to cell B is legal iff every cell between them is free, which is exactly
   the condition for sliding back from B to A. Unlike Water Sort (where
   pouring is only partially reversible and needed a hand-rolled "soft pour"
   guard), this puzzle domain also happens to be small enough for genuine
   exhaustive BFS. So generation (scripts/generate-parking-levels.js) scrambles
   a solved layout with real, legal, random moves and independently proves
   every accepted level solvable via BFS — a real proof, not a heuristic
   sample — which also grades exact difficulty (minimum solution move count).

   Extra spaces mechanic (mirrors Water Sort's extra-bottle mechanic): each
   level has a fixed number of "bay" cells (blank cells not covered by any
   vehicle in the solved layout) equal to its vehicle count. The first 4 are
   always unlocked; the rest start locked (covered, unusable) and unlock one
   at a time, each costing one quiz question via the shared askQuestions()
   (which is also what feeds the Tamagotchi automatically, same as every
   other question-spending flow in this app). The base puzzle is always
   solvable using just the 4 free bays — the rest are pure bonus relief for
   a stuck player.

   Levels are static data (PL_LEVELS below), generated offline, never live
   in the browser. Only the shuffled play order, position in it, and the
   live in-progress vehicle positions/bay-unlock-count are persisted in the
   save; the level layouts themselves ship with the app.
══════════════════════════════════════════════════════════ */

const PL_DEFAULT_BAYS = 4;
const PL_COLORS = [
  "#e0413a", "#5aa8e8", "#6fd88a", "#e8d95a", "#b06fe8",
  "#e86fb0", "#5adfd0", "#e8a45a", "#8a9be0", "#c9a857",
]; // index 0 (target/"red car") is never assigned to a blocker

// Generated by scripts/generate-parking-levels.js. Per level:
// g = [rows, cols]; ex = exit row; bay = [row,col] pairs (first
// PL_DEFAULT_BAYS are pre-unlocked, rest start locked, in purchase order);
// v = vehicles bottom-to-top as [row, col, len, orient('h'|'v'), colorIdx],
// v[0] is always the target (horizontal, len 2).
const PL_LEVELS = [{"g":[6,6],"ex":3,"bay":[[1,4],[1,3],[3,0],[4,5]],"v":[[3,3,2,"h",0],[0,1,2,"v",1],[3,5,2,"v",2],[1,4,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[0,2],[3,1],[5,4],[5,5]],"v":[[3,0,2,"h",0],[3,2,2,"v",1],[5,4,2,"h",2],[5,2,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[5,0],[3,2],[4,0],[0,0]],"v":[[3,0,2,"h",0],[1,2,2,"v",1],[3,2,2,"v",2],[0,0,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[0,4],[3,2],[2,3],[0,5]],"v":[[3,1,2,"h",0],[0,1,2,"h",1],[5,1,2,"h",2],[3,3,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[0,5],[5,0],[5,4],[5,5]],"v":[[3,3,2,"h",0],[5,3,2,"h",1],[2,5,2,"v",2],[3,0,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[5,3],[3,2],[2,3],[5,5]],"v":[[3,3,2,"h",0],[3,0,2,"h",1],[5,3,2,"h",2],[2,2,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[1,2],[3,1],[3,0],[1,0]],"v":[[3,0,2,"h",0],[3,3,2,"v",1],[1,2,2,"v",2],[1,3,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[1,4],[1,0],[5,0],[2,0]],"v":[[3,1,2,"h",0],[1,4,2,"h",1],[1,0,2,"v",2],[4,2,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[3,1],[3,0],[1,2],[0,5]],"v":[[3,0,2,"h",0],[0,1,2,"h",1],[3,3,2,"v",2],[1,1,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[4,2],[5,2],[0,2],[0,1]],"v":[[3,3,2,"h",0],[0,1,2,"v",1],[4,1,2,"v",2],[1,2,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[3,0],[1,2],[4,1],[1,1]],"v":[[3,3,2,"h",0],[1,4,2,"v",1],[0,1,2,"v",2],[2,2,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[5,2],[3,0],[0,5],[3,1]],"v":[[3,3,2,"h",0],[3,2,2,"v",1],[0,2,2,"v",2],[2,5,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[4,5],[4,3],[4,4],[3,1]],"v":[[3,2,2,"h",0],[5,2,2,"h",1],[4,4,2,"h",2],[1,3,2,"v",3]]},{"g":[6,6],"ex":3,"bay":[[2,3],[2,0],[3,2],[1,1]],"v":[[3,0,2,"h",0],[4,1,2,"v",1],[2,3,2,"h",2],[5,4,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[3,2],[0,1],[2,0],[5,5]],"v":[[3,0,2,"h",0],[2,1,2,"h",1],[0,1,2,"v",2],[5,2,2,"h",3]]},{"g":[6,6],"ex":3,"bay":[[2,2],[0,0],[1,1],[0,3],[5,1],[4,2]],"v":[[3,0,2,"h",0],[0,3,2,"h",1],[4,3,2,"h",2],[2,2,2,"v",3],[5,2,2,"h",4],[0,1,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[1,3],[0,3],[0,4],[3,0],[0,2],[4,2]],"v":[[3,0,2,"h",0],[4,4,2,"v",1],[0,0,2,"h",2],[2,2,2,"v",3],[1,0,2,"h",4],[1,4,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[2,4],[1,2],[0,3],[4,0],[4,4],[5,2]],"v":[[3,2,2,"h",0],[1,3,2,"v",1],[4,0,2,"h",2],[2,4,2,"v",3],[0,2,2,"v",4],[3,0,2,"h",5]]},{"g":[6,6],"ex":3,"bay":[[5,4],[4,1],[2,2],[4,4],[1,2],[3,0]],"v":[[3,3,2,"h",0],[1,1,2,"v",1],[0,4,2,"v",2],[0,5,2,"v",3],[2,5,2,"v",4],[3,2,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[2,5],[3,0],[5,4],[5,0],[2,4],[4,5]],"v":[[3,1,2,"h",0],[2,1,2,"h",1],[5,1,2,"h",2],[4,3,2,"v",3],[0,2,2,"v",4],[2,5,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[2,2],[0,2],[5,1],[3,0],[4,5],[1,1]],"v":[[3,2,2,"h",0],[2,1,2,"v",1],[0,2,2,"h",2],[2,5,2,"v",3],[1,3,2,"v",4],[1,2,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[0,2],[2,4],[5,2],[1,1],[1,0],[2,3]],"v":[[3,0,2,"h",0],[1,3,2,"h",1],[1,5,2,"v",2],[2,1,2,"h",3],[4,2,2,"v",4],[3,5,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[0,2],[1,3],[0,5],[0,3],[3,0],[2,3]],"v":[[3,2,2,"h",0],[2,4,2,"v",1],[1,1,2,"v",2],[4,3,2,"v",3],[0,4,2,"h",4],[4,1,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[2,0],[3,2],[5,2],[5,0],[0,5],[4,5]],"v":[[3,2,2,"h",0],[2,3,2,"h",1],[3,1,2,"v",2],[2,5,2,"v",3],[5,3,2,"h",4],[0,1,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[4,2],[3,2],[0,1],[1,4],[1,1],[0,0]],"v":[[3,0,2,"h",0],[2,2,2,"v",1],[2,4,2,"v",2],[4,1,2,"v",3],[2,0,2,"h",4],[4,0,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[5,4],[3,2],[1,3],[3,1],[3,0],[4,5]],"v":[[3,1,2,"h",0],[0,4,2,"h",1],[4,1,2,"h",2],[0,0,2,"v",3],[3,3,2,"v",4],[1,4,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[1,5],[3,2],[0,2],[1,4],[3,0],[2,1]],"v":[[3,1,2,"h",0],[1,0,2,"h",1],[2,4,2,"h",2],[2,3,2,"v",3],[4,3,2,"v",4],[0,3,2,"h",5]]},{"g":[6,6],"ex":3,"bay":[[4,5],[3,2],[3,0],[5,2],[1,1],[0,1]],"v":[[3,2,2,"h",0],[3,5,2,"v",1],[3,1,2,"v",2],[5,3,2,"h",3],[2,1,2,"h",4],[2,4,2,"h",5]]},{"g":[6,6],"ex":3,"bay":[[0,2],[0,0],[1,3],[3,1],[5,0],[2,2]],"v":[[3,2,2,"h",0],[1,4,2,"h",1],[3,4,2,"v",2],[4,2,2,"v",3],[0,3,2,"h",4],[2,0,2,"v",5]]},{"g":[6,6],"ex":3,"bay":[[2,2],[5,5],[0,4],[5,0],[4,5],[5,3]],"v":[[3,0,2,"h",0],[5,0,2,"h",1],[4,0,2,"h",2],[3,2,2,"v",3],[1,0,2,"v",4],[0,4,2,"h",5]]},{"g":[6,6],"ex":3,"bay":[[5,4],[3,2],[0,0],[5,1],[5,0],[4,4],[2,3],[4,2]],"v":[[3,3,2,"h",0],[5,1,2,"h",1],[0,2,3,"h",2],[1,4,2,"v",3],[3,1,2,"h",4],[2,5,2,"v",5],[0,0,2,"h",6],[4,5,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[4,3],[3,1],[4,0],[3,0],[1,5],[5,4],[5,5],[1,2]],"v":[[3,1,2,"h",0],[2,4,2,"v",1],[0,0,2,"h",2],[4,1,2,"h",3],[1,0,2,"h",4],[1,3,3,"v",5],[0,2,2,"h",6],[5,2,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[0,0],[0,3],[1,4],[3,2],[4,3],[0,5],[5,3],[5,4]],"v":[[3,1,2,"h",0],[1,2,2,"h",1],[5,1,2,"h",2],[3,5,2,"v",3],[0,1,2,"h",4],[4,0,2,"v",5],[2,0,3,"h",6],[2,3,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[4,4],[5,4],[0,5],[0,1],[3,0],[2,2],[5,0],[3,1]],"v":[[3,2,2,"h",0],[0,4,2,"v",1],[4,1,2,"h",2],[1,1,2,"v",3],[2,4,2,"h",4],[3,5,2,"v",5],[5,2,3,"h",6],[0,5,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[0,2],[4,5],[5,3],[5,4],[4,3],[4,4],[3,1],[5,0]],"v":[[3,3,2,"h",0],[0,3,2,"h",1],[1,0,2,"h",2],[5,3,2,"h",3],[4,0,2,"h",4],[1,4,2,"v",5],[3,5,3,"v",6],[2,2,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[0,5],[4,0],[5,4],[5,1],[0,0],[2,5],[1,0],[0,2]],"v":[[3,3,2,"h",0],[4,3,2,"h",1],[3,5,2,"v",2],[4,0,2,"v",3],[2,2,3,"v",4],[5,1,2,"h",5],[2,1,2,"v",6],[1,3,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[3,2],[5,4],[1,1],[0,1],[2,5],[5,5],[4,4],[0,0]],"v":[[3,1,2,"h",0],[2,0,2,"h",1],[2,2,2,"h",2],[0,3,2,"v",3],[4,1,2,"v",4],[3,0,3,"v",5],[5,2,2,"h",6],[2,4,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[0,4],[2,0],[0,5],[1,4],[1,3],[1,2],[5,5],[2,1]],"v":[[3,3,2,"h",0],[2,2,3,"v",1],[2,3,2,"h",2],[3,5,2,"v",3],[1,0,2,"h",4],[0,2,2,"h",5],[3,0,2,"h",6],[0,4,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[0,1],[5,4],[0,0],[1,3],[3,0],[0,3],[3,1],[3,2]],"v":[[3,3,2,"h",0],[4,4,2,"h",1],[4,0,3,"h",2],[0,4,2,"h",3],[1,0,2,"h",4],[2,5,2,"v",5],[0,2,2,"v",6],[1,4,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[3,2],[1,5],[4,1],[2,0],[4,3],[0,0],[2,5],[1,0]],"v":[[3,3,2,"h",0],[3,1,2,"h",1],[3,5,2,"v",2],[0,1,2,"v",3],[5,3,2,"h",4],[4,0,2,"v",5],[0,3,3,"v",6],[5,1,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[2,0],[0,4],[3,0],[1,2],[4,1],[4,2],[1,3],[1,1]],"v":[[3,2,2,"h",0],[0,2,2,"v",1],[2,2,3,"h",2],[0,5,2,"v",3],[3,5,2,"v",4],[2,1,2,"v",5],[4,3,2,"v",6],[0,3,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[2,5],[4,5],[5,1],[0,4],[5,0],[4,2],[5,3],[3,0]],"v":[[3,3,2,"h",0],[5,4,2,"h",1],[0,4,2,"v",2],[2,5,2,"v",3],[0,1,3,"v",4],[3,1,2,"h",5],[4,0,2,"h",6],[4,4,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[2,0],[2,3],[2,4],[1,0],[4,5],[3,0],[5,5],[0,5]],"v":[[3,3,2,"h",0],[2,1,3,"v",1],[2,5,2,"v",2],[0,2,2,"h",3],[2,3,2,"h",4],[1,2,2,"h",5],[0,0,2,"h",6],[4,2,2,"v",7]]},{"g":[6,6],"ex":3,"bay":[[0,5],[4,1],[3,1],[0,4],[0,3],[4,0],[2,2],[1,3]],"v":[[3,0,2,"h",0],[0,0,3,"h",1],[3,2,2,"v",2],[2,3,2,"h",3],[4,4,2,"h",4],[5,2,2,"h",5],[3,3,2,"v",6],[5,4,2,"h",7]]},{"g":[6,6],"ex":3,"bay":[[5,0],[1,0],[0,4],[4,4],[1,1],[3,1],[4,5],[5,1]],"v":[[3,3,2,"h",0],[2,5,2,"v",1],[5,4,2,"h",2],[5,2,2,"h",3],[0,4,2,"h",4],[2,2,3,"v",5],[1,2,2,"h",6],[1,4,2,"v",7]]},{"g":[7,7],"ex":3,"bay":[[0,3],[4,1],[2,0],[2,4],[0,2],[0,4],[5,5],[2,6],[4,0]],"v":[[3,2,2,"h",0],[4,1,3,"h",1],[3,6,2,"v",2],[0,0,2,"h",3],[0,5,2,"v",4],[2,0,3,"h",5],[3,4,2,"v",6],[3,0,2,"h",7],[5,0,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[2,1],[5,2],[4,2],[3,3],[3,2],[6,6],[2,2],[1,0],[1,6]],"v":[[3,3,2,"h",0],[2,6,2,"v",1],[5,0,2,"v",2],[5,2,2,"h",3],[2,3,2,"h",4],[2,0,3,"v",5],[0,5,3,"v",6],[4,3,2,"h",7],[3,5,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[1,4],[2,2],[4,4],[1,5],[4,1],[0,6],[2,0],[4,5],[6,0]],"v":[[3,1,2,"h",0],[1,0,3,"h",1],[2,6,2,"v",2],[5,2,2,"v",3],[4,3,2,"h",4],[0,3,2,"h",5],[6,3,2,"h",6],[2,4,2,"h",7],[1,3,3,"v",8]]},{"g":[7,7],"ex":3,"bay":[[3,0],[5,0],[1,2],[2,4],[6,0],[3,3],[1,6],[3,1],[0,0]],"v":[[3,4,2,"h",0],[1,0,2,"v",1],[2,3,2,"h",2],[5,1,2,"h",3],[5,5,2,"h",4],[0,2,3,"h",5],[4,4,3,"h",6],[3,2,2,"v",7],[2,6,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[5,4],[5,3],[4,2],[6,3],[6,4],[1,2],[2,1],[3,3],[1,3]],"v":[[3,4,2,"h",0],[2,4,3,"h",1],[1,0,2,"h",2],[3,6,2,"v",3],[2,2,2,"v",4],[0,5,2,"v",5],[5,3,3,"h",6],[6,0,2,"h",7],[5,6,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[3,0],[1,0],[2,6],[1,1],[3,1],[1,5],[4,0],[0,3],[6,6]],"v":[[3,3,2,"h",0],[0,0,2,"h",1],[5,2,2,"v",2],[2,5,2,"v",3],[4,1,2,"v",4],[3,6,2,"v",5],[1,1,3,"h",6],[2,2,3,"h",7],[4,4,2,"h",8]]},{"g":[7,7],"ex":3,"bay":[[6,4],[6,3],[1,4],[3,3],[4,6],[6,0],[0,3],[1,0],[0,5]],"v":[[3,1,2,"h",0],[4,0,2,"h",1],[2,6,2,"v",2],[4,3,2,"h",3],[3,5,3,"v",4],[4,2,2,"v",5],[1,2,2,"h",6],[6,1,2,"h",7],[0,0,3,"h",8]]},{"g":[7,7],"ex":3,"bay":[[4,3],[5,2],[1,6],[3,0],[6,1],[1,1],[2,2],[0,1],[1,3]],"v":[[3,4,2,"h",0],[2,1,3,"v",1],[5,5,2,"h",2],[2,3,2,"v",3],[2,0,2,"v",4],[2,6,3,"v",5],[6,4,2,"h",6],[2,4,2,"h",7],[0,5,2,"h",8]]},{"g":[7,7],"ex":3,"bay":[[1,2],[5,3],[3,2],[6,0],[5,0],[2,5],[0,3],[0,2],[2,3]],"v":[[3,1,2,"h",0],[4,2,2,"v",1],[5,4,2,"h",2],[2,4,2,"v",3],[2,6,3,"v",4],[4,3,2,"v",5],[6,2,3,"h",6],[2,1,2,"h",7],[4,0,2,"h",8]]},{"g":[7,7],"ex":3,"bay":[[3,2],[3,0],[6,4],[3,3],[4,0],[0,0],[4,1],[0,5],[0,6]],"v":[[3,1,2,"h",0],[0,2,2,"h",1],[2,0,2,"h",2],[4,4,2,"v",3],[1,4,3,"v",4],[2,6,3,"v",5],[1,0,2,"h",6],[4,2,2,"h",7],[1,5,2,"h",8]]},{"g":[7,7],"ex":3,"bay":[[1,2],[0,2],[2,5],[6,0],[0,0],[3,3],[3,1],[4,3],[5,0]],"v":[[3,4,2,"h",0],[0,1,3,"h",1],[1,4,3,"h",2],[5,2,2,"v",3],[5,5,2,"v",4],[5,6,2,"v",5],[2,6,2,"v",6],[5,3,2,"v",7],[1,0,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[1,6],[6,5],[0,6],[5,5],[6,3],[4,5],[2,5],[1,4],[4,2]],"v":[[3,2,2,"h",0],[3,4,2,"v",1],[3,0,2,"h",2],[5,0,2,"h",3],[0,3,3,"v",4],[0,0,3,"h",5],[3,6,2,"v",6],[5,2,2,"v",7],[0,5,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[6,1],[6,6],[0,5],[5,3],[5,0],[2,1],[5,4],[1,2],[1,1]],"v":[[3,1,2,"h",0],[1,4,3,"v",1],[2,0,2,"v",2],[0,5,2,"v",3],[6,0,2,"h",4],[4,1,2,"v",5],[5,2,2,"v",6],[1,6,3,"v",7],[3,3,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[6,1],[1,0],[4,4],[6,2],[6,6],[0,2],[0,4],[1,2],[6,0]],"v":[[3,2,2,"h",0],[1,0,2,"v",1],[3,4,2,"v",2],[2,1,3,"v",3],[6,3,3,"h",4],[5,5,2,"h",5],[5,3,2,"h",6],[2,6,2,"v",7],[5,2,2,"v",8]]},{"g":[7,7],"ex":3,"bay":[[3,0],[5,1],[5,3],[4,2],[2,5],[4,0],[6,1],[2,6],[0,1]],"v":[[3,3,2,"h",0],[2,3,2,"h",1],[0,2,2,"v",2],[5,5,2,"h",3],[4,1,3,"h",4],[1,1,2,"v",5],[1,0,2,"v",6],[3,6,2,"v",7],[1,3,3,"h",8]]},{"g":[7,7],"ex":3,"bay":[[5,0],[6,6],[4,1],[3,2],[6,4],[5,6],[3,0],[6,3],[6,5],[2,5]],"v":[[3,3,2,"h",0],[0,0,2,"v",1],[3,5,2,"v",2],[0,3,2,"h",3],[1,5,2,"h",4],[6,1,2,"h",5],[1,2,2,"h",6],[2,6,3,"v",7],[5,2,2,"h",8],[0,1,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[5,2],[2,6],[4,6],[1,6],[3,2],[0,4],[0,6],[6,5],[1,4],[2,0]],"v":[[3,3,2,"h",0],[3,6,2,"v",1],[3,1,2,"v",2],[6,1,2,"h",3],[2,5,2,"v",4],[0,1,2,"h",5],[1,2,2,"h",6],[3,0,2,"v",7],[5,4,3,"h",8],[2,1,3,"h",9]]},{"g":[7,7],"ex":3,"bay":[[0,0],[5,0],[6,0],[3,2],[0,6],[0,5],[6,2],[0,3],[6,3],[2,6]],"v":[[3,0,2,"h",0],[0,4,2,"v",1],[4,0,2,"v",2],[3,2,2,"v",3],[1,0,3,"h",4],[2,4,2,"h",5],[3,4,3,"v",6],[0,1,2,"h",7],[1,5,2,"h",8],[2,3,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[2,0],[5,5],[0,0],[3,3],[4,6],[0,3],[4,3],[6,6],[5,6],[6,5]],"v":[[3,3,2,"h",0],[3,0,2,"h",1],[1,3,3,"h",2],[2,5,2,"v",3],[1,1,2,"h",4],[5,3,2,"v",5],[2,6,2,"v",6],[2,2,2,"v",7],[4,2,2,"v",8],[4,0,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[1,2],[5,1],[2,5],[5,2],[5,0],[0,0],[2,6],[6,2],[1,1],[0,5]],"v":[[3,2,2,"h",0],[3,0,2,"v",1],[0,3,2,"v",2],[5,4,2,"v",3],[2,5,2,"v",4],[2,4,2,"v",5],[0,2,3,"v",6],[3,6,3,"v",7],[3,1,2,"v",8],[5,3,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[1,4],[5,6],[3,2],[0,6],[5,0],[6,6],[2,4],[3,0],[1,3],[5,5]],"v":[[3,1,2,"h",0],[0,2,2,"v",1],[4,5,2,"h",2],[2,3,2,"v",3],[5,2,2,"h",4],[3,4,3,"v",5],[0,0,2,"h",6],[4,2,2,"h",7],[6,2,2,"h",8],[0,3,3,"h",9]]},{"g":[7,7],"ex":3,"bay":[[1,0],[3,0],[5,4],[0,0],[5,6],[4,5],[2,2],[1,5],[4,3],[3,2]],"v":[[3,4,2,"h",0],[1,0,2,"h",1],[2,3,2,"v",2],[5,2,3,"h",3],[2,0,2,"h",4],[5,5,2,"v",5],[4,1,2,"v",6],[0,3,2,"v",7],[2,6,3,"v",8],[0,5,2,"h",9]]},{"g":[7,7],"ex":3,"bay":[[3,2],[4,1],[4,0],[5,0],[6,1],[2,4],[1,3],[1,4],[0,6],[0,5]],"v":[[3,2,2,"h",0],[2,2,2,"h",1],[2,6,2,"v",2],[0,2,2,"v",3],[1,5,2,"h",4],[4,2,3,"v",5],[6,4,3,"h",6],[4,0,2,"v",7],[2,1,2,"v",8],[2,5,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[4,2],[5,3],[4,6],[4,5],[3,0],[4,0],[3,1],[5,5],[2,3],[6,5]],"v":[[3,4,2,"h",0],[1,0,2,"h",1],[3,2,2,"h",2],[5,6,2,"v",3],[2,6,3,"v",4],[6,1,3,"h",5],[4,1,2,"h",6],[0,5,2,"h",7],[5,0,2,"h",8],[0,3,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[5,5],[5,3],[6,2],[1,1],[2,5],[0,1],[0,5],[6,1],[1,2],[2,4]],"v":[[3,1,2,"h",0],[5,0,2,"v",1],[2,1,2,"h",2],[3,4,2,"v",3],[5,5,2,"h",4],[3,3,2,"v",5],[1,3,2,"h",6],[6,4,2,"h",7],[0,2,3,"h",8],[2,0,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[2,0],[0,5],[5,0],[6,0],[3,0],[1,4],[2,1],[1,3],[1,6],[0,6]],"v":[[3,1,2,"h",0],[5,0,3,"h",1],[2,2,2,"h",2],[4,1,3,"h",3],[2,4,2,"v",4],[2,5,2,"h",5],[0,0,2,"v",6],[1,1,2,"h",7],[3,6,2,"v",8],[3,5,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[0,0],[5,6],[5,5],[1,1],[1,0],[0,5],[6,4],[2,6],[5,3],[4,2]],"v":[[3,0,2,"h",0],[2,0,2,"h",1],[5,1,2,"h",2],[2,2,2,"v",3],[5,0,2,"v",4],[1,5,2,"h",5],[6,5,2,"h",6],[3,4,2,"v",7],[6,1,3,"h",8],[0,2,3,"h",9]]},{"g":[7,7],"ex":3,"bay":[[3,0],[6,3],[5,1],[3,1],[2,1],[4,3],[4,2],[2,2],[1,5],[4,6]],"v":[[3,0,2,"h",0],[2,3,2,"v",1],[2,4,3,"h",2],[5,2,2,"v",3],[0,5,2,"h",4],[1,2,3,"h",5],[0,1,2,"h",6],[3,5,2,"v",7],[5,3,2,"h",8],[5,6,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[1,6],[0,1],[0,6],[2,0],[1,4],[3,1],[6,6],[4,3],[2,6],[1,0]],"v":[[3,2,2,"h",0],[3,4,3,"v",1],[2,4,2,"h",2],[0,5,2,"h",3],[2,0,2,"h",4],[5,3,2,"v",5],[3,6,2,"v",6],[4,0,2,"h",7],[1,1,2,"h",8],[0,3,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[0,3],[1,2],[5,4],[6,0],[6,2],[6,6],[6,1],[4,4],[2,4],[1,3]],"v":[[3,3,2,"h",0],[0,4,2,"v",1],[2,2,2,"h",2],[2,6,2,"v",3],[0,0,3,"h",4],[2,5,2,"v",5],[2,0,2,"h",6],[3,0,3,"h",7],[6,4,2,"h",8],[1,5,2,"h",9]]},{"g":[7,7],"ex":3,"bay":[[6,3],[2,6],[0,6],[4,2],[0,2],[0,5],[5,3],[1,2],[6,4],[1,0]],"v":[[3,0,2,"h",0],[0,1,2,"v",1],[6,1,3,"h",2],[2,4,2,"v",3],[1,3,3,"v",4],[3,6,2,"v",5],[1,5,2,"h",6],[4,3,2,"h",7],[3,2,2,"v",8],[2,5,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[3,1],[4,6],[3,2],[0,5],[0,6],[5,1],[2,6],[1,6],[1,0],[2,1]],"v":[[3,3,2,"h",0],[2,0,3,"v",1],[0,4,2,"h",2],[2,4,2,"h",3],[5,3,2,"v",4],[5,0,2,"v",5],[5,4,3,"h",6],[5,2,2,"v",7],[2,2,3,"v",8],[3,6,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[0,3],[0,0],[3,2],[1,5],[0,5],[1,3],[6,0],[3,0],[2,0],[0,4]],"v":[[3,1,2,"h",0],[6,3,3,"h",1],[4,3,2,"v",2],[3,6,2,"v",3],[0,2,2,"h",4],[4,1,2,"v",5],[5,6,2,"v",6],[2,4,3,"h",7],[1,2,2,"v",8],[3,5,3,"v",9]]},{"g":[7,7],"ex":3,"bay":[[0,5],[3,0],[4,6],[1,2],[1,3],[2,0],[0,3],[6,6],[6,2],[5,6]],"v":[[3,0,2,"h",0],[1,0,2,"h",1],[3,4,3,"v",2],[2,3,2,"h",3],[3,2,2,"v",4],[3,3,2,"v",5],[5,1,3,"h",6],[1,4,2,"h",7],[3,5,3,"v",8],[2,6,2,"v",9]]},{"g":[7,7],"ex":3,"bay":[[0,1],[1,4],[0,6],[0,2],[4,5],[2,5],[1,3],[1,6],[6,0],[2,6]],"v":[[3,3,2,"h",0],[3,6,3,"v",1],[6,2,3,"h",2],[0,0,2,"h",3],[5,1,2,"v",4],[2,0,2,"h",5],[1,0,2,"h",6],[6,5,2,"h",7],[3,0,3,"h",8],[0,5,2,"v",9]]}];
const PL_LEVEL_COUNT = PL_LEVELS.length;

function plGenerateLevel(levelIndex) {
  return PL_LEVELS[levelIndex].v.map(([r, c, len, orient, colorIdx]) => ({
    r, c, len, orient, color: PL_COLORS[colorIdx],
  }));
}

/* ── core pure logic — operate on vehicle objects {r,c,len,orient,color} ── */
function plVehicleCells(v) {
  const cells = [];
  for (let i = 0; i < v.len; i++) cells.push(v.orient === 'h' ? [v.r, v.c + i] : [v.r + i, v.c]);
  return cells;
}
function plOccupiedSet(vehicles, excludeIdx) {
  const set = new Set();
  vehicles.forEach((v, i) => { if (i !== excludeIdx) plVehicleCells(v).forEach(([r, c]) => set.add(r + ',' + c)); });
  return set;
}
function plMaxRun(vehicles, lockedCells, gridDims, vIdx, dir) {
  const v = vehicles[vIdx];
  const occ = plOccupiedSet(vehicles, vIdx);
  let dist = 0;
  while (true) {
    const next = dist + 1;
    const r = v.orient === 'v' ? (dir > 0 ? v.r + v.len - 1 + next : v.r - next) : v.r;
    const c = v.orient === 'h' ? (dir > 0 ? v.c + v.len - 1 + next : v.c - next) : v.c;
    if (r < 0 || r >= gridDims.rows || c < 0 || c >= gridDims.cols) break;
    const key = r + ',' + c;
    if (occ.has(key) || lockedCells.has(key)) break;
    dist = next;
  }
  return dist;
}
// Clamps a tapped destination cell to the vehicle's own lane; slides as far
// toward it as legally possible (stopping when blocked), mirroring
// wsPour's "mutate + return amount moved" pattern.
function plSlideVehicleTo(vehicles, lockedCells, gridDims, vIdx, r, c) {
  const v = vehicles[vIdx];
  let dir, targetDist;
  if (v.orient === 'h') {
    if (r !== v.r) return 0;
    dir = c >= v.c ? 1 : -1;
    targetDist = dir > 0 ? c - (v.c + v.len - 1) : v.c - c;
  } else {
    if (c !== v.c) return 0;
    dir = r >= v.r ? 1 : -1;
    targetDist = dir > 0 ? r - (v.r + v.len - 1) : v.r - r;
  }
  if (targetDist <= 0) return 0;
  const dist = Math.min(targetDist, plMaxRun(vehicles, lockedCells, gridDims, vIdx, dir));
  if (dist <= 0) return 0;
  if (v.orient === 'h') v.c += dir * dist; else v.r += dir * dist;
  return dist;
}
function plIsSolved(vehicles, gridDims) {
  const target = vehicles[0];
  return target.c + target.len - 1 === gridDims.cols - 1;
}

/* ── level-scoped helpers ── */
function plGridDims(pl) {
  const level = PL_LEVELS[pl.currentLevelIndex];
  return { rows: level.g[0], cols: level.g[1] };
}
function plLockedCellSet(pl) {
  const level = PL_LEVELS[pl.currentLevelIndex];
  return new Set(level.bay.slice(pl.bayUnlocked).map(([r, c]) => r + ',' + c));
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.parkingLot
══════════════════════════════════════════════════════════ */
function plOnVehicleTap(vIdx) {
  const pl = G.parkingLot;
  if (pl.selectedVehicle === vIdx) { pl.selectedVehicle = null; plRender(); return; }
  pl.selectedVehicle = vIdx;
  plRender();
}
window.plOnVehicleTap = plOnVehicleTap;

function plOnCellTap(r, c) {
  const pl = G.parkingLot;
  if (pl.selectedVehicle === null) return;
  const moved = plSlideVehicleTo(pl.vehicles, plLockedCellSet(pl), plGridDims(pl), pl.selectedVehicle, r, c);
  pl.selectedVehicle = null;
  if (moved > 0) {
    saveState(); // explicit — mid-level progress must survive a reload
    if (plIsSolved(pl.vehicles, plGridDims(pl))) { plOnLevelSolved(); return; }
  }
  plRender();
}
window.plOnCellTap = plOnCellTap;

function plOnLevelSolved() {
  G.stats.parkingLevelsCompleted = (G.stats.parkingLevelsCompleted || 0) + 1;
  checkTrophies();
  showToast("🚗 Ausgeparkt!");
  saveState();
  plRender();
  setTimeout(plAdvanceToNextLevel, 900);
}

function plAdvanceToNextLevel() {
  const pl = G.parkingLot;
  pl.playOrderPos++;
  if (pl.playOrderPos >= pl.playOrder.length) {
    const prevLast = pl.playOrder[pl.playOrder.length - 1];
    const order = shuffleArray([...Array(PL_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    pl.playOrder = order;
    pl.playOrderPos = 0;
  }
  plStartLevel(pl.playOrder[pl.playOrderPos]);
}

function plStartLevel(levelIndex) {
  const pl = G.parkingLot;
  pl.currentLevelIndex = levelIndex;
  pl.vehicles = plGenerateLevel(levelIndex);
  pl.bayUnlocked = PL_DEFAULT_BAYS;
  pl.selectedVehicle = null;
  saveState();
  plRender();
}

function plRestartLevel() {
  const pl = G.parkingLot;
  if (pl.currentLevelIndex == null) return;
  plStartLevel(pl.currentLevelIndex);
  showToast("🔄 Level neu gestartet.");
}
window.plRestartLevel = plRestartLevel;

function plEnsureQueueAndLevel() {
  const pl = G.parkingLot;
  if (!pl.playOrder.length) {
    pl.playOrder = shuffleArray([...Array(PL_LEVEL_COUNT).keys()]);
    pl.playOrderPos = 0;
  }
  if (pl.currentLevelIndex == null || !pl.vehicles.length) {
    plStartLevel(pl.playOrder[pl.playOrderPos]);
  } else {
    plRender();
  }
}
window.plEnsureQueueAndLevel = plEnsureQueueAndLevel;

function plBuyExtraBay() {
  const pl = G.parkingLot;
  const level = PL_LEVELS[pl.currentLevelIndex];
  if (pl.bayUnlocked >= level.bay.length) {
    showToast(`Maximal ${level.bay.length} Parkplätze für dieses Level!`);
    return;
  }
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🚗 Zusatzparkplatz", 1, () => {
    pl.bayUnlocked++;
    G.stats.parkingBaysUnlockedTotal = (G.stats.parkingBaysUnlockedTotal || 0) + 1;
    checkTrophies();
    saveState();
    plRender();
    showToast("🚗 Neuer Parkplatz freigeschaltet!");
  }, null);
}
window.plBuyExtraBay = plBuyExtraBay;

/* ══════════════════════════════════════════════════════════
   RENDERING — two overlapping CSS grids: a background cell layer
   (tappable, shows plain/bay-open/bay-locked/exit state) and a vehicle
   overlay layer (tappable, positioned via grid-column/row spans). Vehicle
   overlays sit visually on top of occupied cells, so a tap there never
   reaches the background cell underneath — no click-suppression needed.
══════════════════════════════════════════════════════════ */
function plRender() {
  const pl = G.parkingLot;
  const level = PL_LEVELS[pl.currentLevelIndex];
  const infoEl = document.getElementById("pl-level-info");
  const cellLayer = document.getElementById("pk-cell-layer");
  const vehicleLayer = document.getElementById("pk-vehicle-layer");
  const buyBtn = document.getElementById("pl-buy-bay-btn");
  if (!cellLayer || !vehicleLayer || !level) return;

  const [rows, cols] = level.g;
  const gridStyle = `grid-template-columns:repeat(${cols},1fr);grid-template-rows:repeat(${rows},1fr);`;
  cellLayer.style.cssText = gridStyle;
  vehicleLayer.style.cssText = gridStyle;

  if (infoEl) {
    infoEl.textContent = pl.currentLevelIndex == null ? "" : `Level ${pl.currentLevelIndex + 1} / ${PL_LEVEL_COUNT}`;
  }

  const bayIndexOf = new Map(level.bay.map(([r, c], idx) => [r + ',' + c, idx]));

  const cellsHtml = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const key = r + ',' + c;
      let cls = "pk-cell";
      if (bayIndexOf.has(key)) {
        cls += bayIndexOf.get(key) < pl.bayUnlocked ? " pk-cell--bay-open" : " pk-cell--bay-locked";
      } else {
        cls += " pk-cell--plain";
      }
      if (r === level.ex && c === cols - 1) cls += " pk-cell--exit";
      cellsHtml.push(`<div class="${cls}" data-r="${r}" data-c="${c}"></div>`);
    }
  }
  cellLayer.innerHTML = cellsHtml.join("");
  cellLayer.querySelectorAll(".pk-cell").forEach(el => {
    el.onclick = () => plOnCellTap(parseInt(el.dataset.r, 10), parseInt(el.dataset.c, 10));
  });

  vehicleLayer.innerHTML = pl.vehicles.map((v, idx) => {
    const colSpan = v.orient === 'h' ? v.len : 1;
    const rowSpan = v.orient === 'v' ? v.len : 1;
    let cls = "pk-vehicle";
    if (idx === 0) cls += " pk-vehicle--target";
    if (pl.selectedVehicle === idx) cls += " pk-vehicle--selected";
    const style = `grid-column:${v.c + 1} / span ${colSpan};grid-row:${v.r + 1} / span ${rowSpan};background:${v.color};`;
    return `<div class="${cls}" style="${style}" data-idx="${idx}"></div>`;
  }).join("");
  vehicleLayer.querySelectorAll(".pk-vehicle").forEach(el => {
    el.onclick = () => plOnVehicleTap(parseInt(el.dataset.idx, 10));
  });

  if (buyBtn) {
    const atCap = pl.bayUnlocked >= level.bay.length;
    buyBtn.disabled = atCap;
    buyBtn.classList.toggle("ws-buy-bottle-btn--off", atCap);
    buyBtn.textContent = atCap
      ? "➕ Maximal erreicht"
      : `➕ Parkplatz (1 Frage) · ${pl.bayUnlocked}/${level.bay.length}`;
  }
}
window.plRender = plRender;
