'use strict';

/* ══════════════════════════════════════════════════════════
   WATER SORT — potion-sorting puzzle ("Tränke")

   Bottles hold up to WS_CAPACITY stacked units of colored liquid.
   Pour rules: A→B legal only if B has room AND (B empty OR B's top
   color == A's top color); a pour always moves the full contiguous
   top-color run from A, capped by B's remaining space. Win when every
   bottle is empty or full+monochrome.

   Levels are static data (WS_LEVELS below) rather than generated live in
   the browser. Earlier attempts at live seeded-PRNG generation (simulating
   legal pours starting from a solved state, then unscrambling) kept
   producing boards with an isolated color bottle left untouched — and
   therefore still solved on load — because once the spare bottles
   saturate, a randomly-touched color has nowhere left to go, so a specific
   color could go untouched indefinitely. Real per-level data sidesteps
   this: each entry was generated offline (scripts/generate-ws-levels.js)
   by dealing a genuinely shuffled deck of color units into bottles, then
   independently verified solvable via repeated randomized playouts before
   being accepted — see that script for the full generation/verification
   process. Only the shuffled play order, position in it, and the live
   in-progress bottle state are persisted in the save; the level layouts
   themselves ship with the app.
══════════════════════════════════════════════════════════ */

const WS_CAPACITY          = 4;
const WS_MAX_EXTRA_BOTTLES = 3;
const WS_COLORS = [
  "#e8735a", "#5aa8e8", "#6fd88a", "#e8d95a", "#b06fe8",
  "#e86fb0", "#5adfd0", "#e8a45a", "#8a9be0",
];

// Generated by scripts/generate-ws-levels.js — each entry is one level's
// starting bottle layout (color indices into WS_COLORS; [] = empty bottle).
const WS_LEVELS = [[[0,3,0,3],[4,3,1,2],[2,0,3,0],[2,4,1,4],[1,2,4,1],[],[]],[[0,4,1,3],[2,0,1,0],[3,2,0,1],[4,1,3,4],[2,4,2,3],[],[]],[[4,3,1,3],[1,1,0,4],[0,4,0,3],[3,2,2,2],[4,2,0,1],[],[]],[[4,3,2,0],[4,0,0,3],[4,3,1,2],[3,1,1,2],[0,1,4,2],[],[]],[[2,4,1,1],[3,1,4,1],[4,4,3,2],[0,0,3,3],[2,2,0,0],[],[]],[[1,2,1,2],[4,4,3,0],[3,1,0,0],[1,3,2,3],[2,0,4,4],[],[]],[[4,3,4,1],[2,0,4,0],[4,0,2,3],[1,1,2,2],[3,3,1,0],[],[]],[[2,0,0,3],[1,4,0,0],[3,1,1,2],[4,4,3,3],[1,2,2,4],[],[]],[[2,0,3,1],[3,4,2,1],[4,3,0,0],[1,3,2,4],[1,2,4,0],[],[]],[[2,2,0,1],[3,4,3,3],[0,3,1,2],[4,2,1,0],[4,1,0,4],[],[]],[[1,0,3,5],[2,0,1,4],[3,2,1,2],[5,3,4,0],[4,3,0,2],[1,4,5,5],[],[]],[[1,2,3,3],[3,0,4,5],[3,2,4,0],[1,4,0,2],[2,5,4,5],[0,1,5,1],[],[]],[[0,1,2,5],[0,5,1,3],[5,2,3,0],[4,1,4,4],[5,2,1,3],[2,4,3,0],[],[]],[[5,5,3,0],[2,4,4,0],[2,0,3,1],[1,5,4,1],[2,5,0,2],[3,1,4,3],[],[]],[[2,3,5,4],[4,4,1,2],[5,3,1,3],[2,2,0,0],[5,5,0,1],[0,4,1,3],[],[]],[[1,1,2,3],[2,0,0,4],[5,3,0,4],[4,5,3,1],[3,2,2,5],[4,1,0,5],[],[]],[[2,1,5,2],[1,4,0,0],[4,3,0,5],[4,4,1,3],[5,0,3,2],[2,1,5,3],[],[]],[[5,5,0,2],[1,4,0,1],[1,3,3,2],[4,5,5,0],[1,0,4,3],[3,4,2,2],[],[]],[[2,1,5,1],[2,4,5,5],[0,3,2,0],[4,3,1,2],[0,4,4,3],[1,0,5,3],[],[]],[[5,2,4,2],[5,1,3,4],[1,3,3,0],[3,4,5,0],[2,0,1,2],[4,0,1,5],[],[]],[[2,2,3,3],[0,4,4,0],[5,0,1,1],[5,5,4,5],[2,3,1,1],[4,0,3,2],[],[]],[[5,2,0,2],[1,2,0,3],[4,0,4,1],[5,3,5,1],[4,1,3,5],[3,4,2,0],[],[]],[[3,1,4,3],[2,5,0,4],[1,5,2,4],[5,2,2,0],[0,5,3,1],[0,3,1,4],[],[]],[[4,3,4,2],[5,3,0,1],[0,0,5,4],[4,1,5,2],[1,2,2,0],[3,5,3,1],[],[]],[[3,2,1,2],[5,4,1,3],[3,5,3,5],[4,0,4,5],[0,1,2,1],[2,0,4,0],[],[]],[[6,5,3,6],[1,2,0,5],[1,6,2,3],[4,0,0,3],[0,5,1,3],[4,4,6,2],[4,1,5,2],[],[]],[[1,6,4,1],[1,5,2,1],[5,3,3,4],[2,0,0,2],[6,2,0,5],[0,3,3,5],[4,4,6,6],[],[]],[[2,4,3,4],[6,1,6,0],[4,6,4,2],[2,5,3,5],[3,6,0,0],[5,3,1,1],[0,5,1,2],[],[]],[[0,3,2,3],[0,5,6,5],[6,1,5,4],[3,2,4,0],[5,1,1,6],[2,6,0,2],[4,1,3,4],[],[]],[[1,1,0,3],[0,6,4,5],[2,0,2,4],[5,4,5,0],[4,1,6,3],[2,3,1,2],[6,5,3,6],[],[]],[[0,6,4,5],[3,5,5,1],[6,3,1,0],[0,2,4,2],[1,5,3,3],[2,1,2,6],[6,4,4,0],[],[]],[[1,6,4,4],[2,0,1,5],[1,5,2,4],[0,3,0,6],[6,2,5,4],[3,5,3,0],[2,3,6,1],[],[]],[[5,4,1,2],[6,4,5,5],[4,3,1,3],[3,0,6,0],[2,5,1,4],[6,2,3,1],[6,0,0,2],[],[]],[[2,4,5,6],[2,2,1,0],[5,6,3,1],[6,5,2,3],[1,3,6,0],[4,4,0,1],[0,5,4,3],[],[]],[[5,1,1,0],[3,5,0,6],[2,2,4,6],[3,3,2,4],[1,0,1,4],[0,6,6,3],[2,5,5,4],[],[]],[[3,5,5,5],[5,2,4,0],[3,6,6,6],[1,2,6,4],[2,1,1,2],[3,0,3,1],[0,0,4,4],[],[]],[[5,1,3,3],[5,0,4,2],[4,5,0,1],[0,2,4,2],[4,0,5,1],[2,6,3,6],[6,6,3,1],[],[]],[[2,3,1,1],[1,6,3,5],[3,3,0,0],[4,1,6,4],[0,4,2,5],[2,4,5,5],[0,2,6,6],[],[]],[[0,2,6,4],[5,0,3,5],[3,5,0,1],[4,1,2,6],[3,1,4,0],[2,4,5,6],[3,2,1,6],[],[]],[[6,3,2,5],[2,4,6,4],[2,6,5,0],[0,1,4,0],[4,1,1,2],[3,5,3,3],[1,0,6,5],[],[]],[[1,1,6,2],[5,4,0,5],[4,4,1,2],[6,3,0,2],[1,6,3,3],[3,0,5,2],[0,4,6,5],[],[]],[[6,0,3,6],[5,0,1,2],[4,0,6,0],[2,3,1,6],[1,4,5,4],[3,5,2,4],[1,2,5,3],[],[]],[[3,5,0,5],[1,6,0,1],[6,3,5,2],[2,0,3,3],[5,4,6,0],[2,1,2,6],[4,4,4,1],[],[]],[[0,2,5,6],[6,3,0,4],[5,2,3,3],[4,0,1,2],[1,1,1,6],[3,4,2,5],[5,6,4,0],[],[]],[[4,2,5,5],[3,6,0,2],[6,0,1,2],[5,3,2,1],[6,4,6,4],[0,1,4,3],[0,5,3,1],[],[]],[[4,0,0,5],[3,3,5,6],[0,4,5,4],[7,3,7,1],[0,2,4,7],[2,7,2,1],[5,6,1,2],[6,3,6,1],[],[]],[[6,7,4,7],[1,4,3,7],[1,2,0,6],[0,1,5,7],[0,5,6,3],[2,2,2,1],[4,5,4,5],[3,3,0,6],[],[]],[[6,7,1,0],[6,2,1,2],[7,4,7,4],[5,3,2,3],[4,3,5,0],[3,7,4,0],[1,5,0,5],[6,6,1,2],[],[]],[[7,4,0,3],[5,7,6,1],[4,3,4,5],[0,5,6,1],[0,2,3,5],[1,6,0,7],[4,1,2,3],[2,6,7,2],[],[]],[[2,6,7,7],[5,1,3,2],[3,3,0,0],[6,6,5,3],[1,1,5,0],[4,4,0,5],[2,1,4,4],[2,6,7,7],[],[]],[[1,0,6,0],[5,2,7,0],[4,4,7,2],[7,1,1,4],[0,1,5,3],[2,4,3,3],[6,7,3,5],[5,2,6,6],[],[]],[[0,2,6,1],[6,3,5,3],[7,1,2,7],[7,4,4,1],[4,2,3,4],[7,6,0,0],[2,0,6,1],[5,5,3,5],[],[]],[[1,1,6,1],[2,5,4,5],[6,4,2,0],[3,0,6,2],[7,6,0,4],[4,7,5,5],[1,3,2,3],[0,3,7,7],[],[]],[[3,7,7,1],[4,0,1,0],[3,4,1,3],[5,2,2,6],[0,0,2,6],[3,5,7,4],[5,4,1,6],[7,2,6,5],[],[]],[[1,7,5,3],[4,0,0,6],[0,3,2,0],[6,1,2,4],[4,1,2,2],[3,6,5,5],[7,7,7,3],[4,1,6,5],[],[]],[[3,0,5,6],[2,0,4,6],[6,4,2,0],[4,4,7,7],[0,3,3,1],[5,7,2,1],[6,5,7,1],[1,3,2,5],[],[]],[[5,0,0,4],[2,4,1,1],[4,7,4,5],[2,3,3,1],[6,7,3,6],[2,2,6,7],[0,6,1,0],[3,5,5,7],[],[]],[[3,4,3,1],[5,3,2,0],[2,6,3,7],[2,0,5,1],[4,4,1,4],[0,2,7,6],[6,7,1,6],[7,5,5,0],[],[]],[[3,3,3,1],[5,1,0,2],[0,7,2,2],[1,6,5,6],[4,4,7,7],[6,1,6,0],[7,5,4,2],[0,4,3,5],[],[]],[[5,5,0,3],[6,0,4,3],[0,4,3,1],[4,6,1,7],[5,4,1,2],[0,2,6,7],[5,7,3,2],[1,2,7,6],[],[]],[[0,8,2,1],[7,1,3,6],[4,3,7,6],[5,7,6,0],[2,0,4,3],[3,2,5,8],[5,8,1,1],[8,4,6,5],[4,0,7,2],[],[]],[[5,0,3,4],[7,6,1,0],[4,5,1,6],[6,0,6,5],[3,5,1,4],[8,2,0,3],[8,7,2,2],[2,4,7,1],[8,7,3,8],[],[]],[[0,2,6,2],[6,0,5,8],[7,3,1,3],[8,3,2,0],[8,6,7,4],[1,7,4,2],[8,1,6,7],[3,4,1,5],[0,4,5,5],[],[]],[[6,1,1,1],[4,5,2,2],[3,8,7,0],[1,8,6,2],[7,6,0,3],[5,6,3,4],[3,7,4,8],[8,4,2,5],[0,0,5,7],[],[]],[[8,6,2,3],[7,2,4,5],[5,3,0,8],[0,1,5,2],[4,4,0,1],[1,8,8,1],[7,0,7,6],[6,3,4,2],[7,6,5,3],[],[]],[[1,5,0,1],[7,0,6,0],[5,6,4,2],[6,4,4,5],[3,1,7,8],[2,2,4,1],[8,3,8,6],[8,7,7,2],[0,3,3,5],[],[]],[[0,8,5,6],[3,8,0,7],[1,2,1,0],[6,4,7,3],[5,4,2,5],[5,1,6,2],[2,8,3,7],[8,6,4,1],[4,3,0,7],[],[]],[[2,2,3,1],[1,8,6,3],[8,4,4,6],[1,0,7,3],[4,5,8,4],[6,0,5,8],[7,6,2,1],[5,2,3,0],[5,7,7,0],[],[]],[[3,6,0,0],[2,2,7,7],[6,6,2,7],[5,8,0,1],[1,3,7,5],[4,3,4,3],[8,8,5,6],[0,4,8,1],[5,1,4,2],[],[]],[[5,7,1,5],[6,6,8,0],[1,4,4,8],[5,0,3,4],[7,1,5,6],[3,0,8,2],[2,3,7,6],[4,2,7,0],[1,3,8,2],[],[]],[[2,3,6,8],[1,2,4,2],[8,0,3,5],[3,4,4,2],[4,6,1,5],[6,7,7,0],[0,0,7,5],[8,7,6,5],[8,1,1,3],[],[]],[[7,8,7,5],[8,8,0,3],[0,2,4,3],[1,6,4,0],[4,6,4,2],[2,7,2,6],[3,5,8,5],[3,1,1,5],[6,1,7,0],[],[]],[[1,2,1,4],[0,6,2,1],[7,8,7,6],[5,3,3,7],[5,1,0,4],[2,3,4,8],[2,0,5,4],[8,3,8,5],[6,7,6,0],[],[]],[[7,8,7,1],[8,3,2,6],[1,0,6,4],[5,2,8,3],[4,4,2,0],[6,5,4,7],[0,3,0,2],[6,1,1,5],[3,7,5,8],[],[]],[[0,1,3,8],[2,7,6,8],[1,5,4,2],[4,3,3,7],[1,6,8,5],[5,7,0,4],[6,8,5,6],[0,4,7,0],[3,2,2,1],[],[]],[[0,8,7,5],[1,7,1,2],[4,0,8,1],[6,1,8,7],[0,4,3,5],[2,6,2,6],[3,5,6,4],[7,8,5,3],[4,2,0,3],[],[]],[[7,2,5,7],[1,0,6,5],[6,8,8,4],[2,5,3,8],[2,7,1,4],[5,3,8,0],[6,1,6,1],[3,4,4,2],[0,7,0,3],[],[]],[[1,5,5,2],[6,2,0,2],[8,3,5,2],[1,4,3,7],[3,6,3,7],[4,8,8,1],[0,4,8,0],[5,0,4,7],[1,6,6,7],[],[]],[[7,8,7,5],[0,2,6,6],[8,0,2,3],[1,7,1,7],[1,3,4,0],[8,4,2,3],[3,5,6,0],[5,2,6,4],[4,1,8,5],[],[]],[[3,7,1,4],[5,4,7,5],[3,8,8,8],[6,0,1,7],[2,5,6,7],[0,3,6,8],[1,0,3,5],[4,6,2,2],[2,1,4,0],[],[]]];
const WS_LEVEL_COUNT = WS_LEVELS.length;

function wsGenerateLevel(levelIndex) {
  return WS_LEVELS[levelIndex].map(bottle => bottle.map(ci => WS_COLORS[ci]));
}

/* ── core pour rules ── */
function wsTopRun(bottle) {
  if (!bottle.length) return { color: null, len: 0 };
  const color = bottle[bottle.length - 1];
  let len = 1;
  while (len < bottle.length && bottle[bottle.length - 1 - len] === color) len++;
  return { color, len };
}
function wsCanPour(bottles, from, to) {
  if (from === to) return false;
  const src = bottles[from], dst = bottles[to];
  if (!src || !dst || !src.length || dst.length >= WS_CAPACITY) return false;
  const top = src[src.length - 1];
  return dst.length === 0 || dst[dst.length - 1] === top;
}
function wsPour(bottles, from, to) {
  if (!wsCanPour(bottles, from, to)) return 0;
  const { color, len } = wsTopRun(bottles[from]);
  const amt = Math.min(len, WS_CAPACITY - bottles[to].length);
  for (let i = 0; i < amt; i++) bottles[to].push(bottles[from].pop());
  return amt;
}
function wsIsSolved(bottles) {
  return bottles.every(b => b.length === 0 || (b.length === WS_CAPACITY && b.every(c => c === b[0])));
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.waterSort
══════════════════════════════════════════════════════════ */
function wsOnBottleTap(idx) {
  const ws = G.waterSort;
  if (ws.selectedBottle === null) {
    if (ws.bottles[idx] && ws.bottles[idx].length) { ws.selectedBottle = idx; wsRender(); }
    return;
  }
  if (ws.selectedBottle === idx) { ws.selectedBottle = null; wsRender(); return; }
  const amt = wsPour(ws.bottles, ws.selectedBottle, idx);
  ws.selectedBottle = null;
  if (amt > 0) {
    saveState(); // explicit — mid-level progress must survive a reload
    if (wsIsSolved(ws.bottles)) { wsOnLevelSolved(); return; }
  }
  wsRender();
}
window.wsOnBottleTap = wsOnBottleTap;

function wsOnLevelSolved() {
  G.stats.waterSortLevelsCompleted = (G.stats.waterSortLevelsCompleted || 0) + 1;
  checkTrophies();
  showToast("🧪 Level gelöst!");
  saveState();
  wsRender();
  setTimeout(wsAdvanceToNextLevel, 900);
}

function wsAdvanceToNextLevel() {
  const ws = G.waterSort;
  ws.playOrderPos++;
  if (ws.playOrderPos >= ws.playOrder.length) {
    const prevLast = ws.playOrder[ws.playOrder.length - 1];
    const order = shuffleArray([...Array(WS_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    ws.playOrder = order;
    ws.playOrderPos = 0;
  }
  wsStartLevel(ws.playOrder[ws.playOrderPos]);
}

function wsStartLevel(levelIndex) {
  const ws = G.waterSort;
  ws.currentLevelIndex = levelIndex;
  ws.bottles = wsGenerateLevel(levelIndex);
  ws.extraBottlesUsed = 0;
  ws.selectedBottle = null;
  saveState();
  wsRender();
}

function wsRestartLevel() {
  const ws = G.waterSort;
  if (ws.currentLevelIndex == null) return;
  wsStartLevel(ws.currentLevelIndex);
  showToast("🔄 Level neu gestartet.");
}
window.wsRestartLevel = wsRestartLevel;

function wsEnsureQueueAndLevel() {
  const ws = G.waterSort;
  if (!ws.playOrder.length) {
    ws.playOrder = shuffleArray([...Array(WS_LEVEL_COUNT).keys()]);
    ws.playOrderPos = 0;
  }
  if (ws.currentLevelIndex == null || !ws.bottles.length) {
    wsStartLevel(ws.playOrder[ws.playOrderPos]);
  } else {
    wsRender();
  }
}
window.wsEnsureQueueAndLevel = wsEnsureQueueAndLevel;

function wsBuyExtraBottle() {
  const ws = G.waterSort;
  if (ws.extraBottlesUsed >= WS_MAX_EXTRA_BOTTLES) {
    showToast(`Maximal ${WS_MAX_EXTRA_BOTTLES} Extra-Fläschchen pro Level!`);
    return;
  }
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🧪 Extra-Fläschchen", 1, () => {
    ws.bottles.push([]);
    ws.extraBottlesUsed++;
    G.stats.waterSortExtraBottlesBought = (G.stats.waterSortExtraBottlesBought || 0) + 1;
    checkTrophies();
    saveState();
    wsRender();
    showToast("🧪 Neues Fläschchen erhalten!");
  }, null);
}
window.wsBuyExtraBottle = wsBuyExtraBottle;

/* ══════════════════════════════════════════════════════════
   RENDERING
══════════════════════════════════════════════════════════ */
function wsRender() {
  const ws = G.waterSort;
  const infoEl = document.getElementById("ws-level-info");
  const gridEl = document.getElementById("ws-bottle-grid");
  const buyBtn = document.getElementById("ws-buy-bottle-btn");
  if (!gridEl) return;

  if (infoEl) {
    infoEl.textContent = ws.currentLevelIndex == null
      ? ""
      : `Level ${ws.currentLevelIndex + 1} / ${WS_LEVEL_COUNT}`;
  }

  gridEl.innerHTML = (ws.bottles || []).map((bottle, idx) => {
    const slots = [];
    for (let i = 0; i < WS_CAPACITY; i++) {
      const color = bottle[i];
      slots.push(color
        ? `<div class="ws-segment" style="background:${color}"></div>`
        : `<div class="ws-segment ws-segment--empty"></div>`);
    }
    const selected = ws.selectedBottle === idx ? " ws-bottle--selected" : "";
    return `<div class="ws-bottle${selected}" data-idx="${idx}">
      <div class="ws-bottle-stack">${slots.join("")}</div>
    </div>`;
  }).join("");

  gridEl.querySelectorAll(".ws-bottle").forEach(el => {
    el.onclick = () => wsOnBottleTap(parseInt(el.dataset.idx, 10));
  });

  if (buyBtn) {
    const atCap = (ws.extraBottlesUsed || 0) >= WS_MAX_EXTRA_BOTTLES;
    buyBtn.disabled = atCap;
    buyBtn.classList.toggle("ws-buy-bottle-btn--off", atCap);
    buyBtn.textContent = atCap
      ? "➕ Maximal erreicht"
      : `➕ Extra-Fläschchen (1 Frage) · ${ws.extraBottlesUsed || 0}/${WS_MAX_EXTRA_BOTTLES}`;
  }
}
window.wsRender = wsRender;
