'use strict';

/* ══════════════════════════════════════════════════════════
   WATER SORT — potion-sorting puzzle ("Tränke")

   Bottles hold up to WS_CAPACITY stacked units of colored liquid.
   Pour rules: A→B legal only if B has room AND (B empty OR B's top
   color == A's top color); a pour always moves the full contiguous
   top-color run from A, capped by B's remaining space. Win when every
   bottle is empty or full+monochrome — a still-locked bottle (see below)
   never counts, regardless of its hidden contents.

   Only 1 free spare bottle per level, always — buying an extra one via
   wsBuyExtraBottle() (spends a quiz question) is meant to matter, not be a
   rarely-needed safety net.

   Two mechanics layer on top of the classic rules, introduced gradually
   across the level pool (see scripts/generate-ws-levels.js's difficulty
   table — early levels are classic-only):
   - Fog: some units start hidden ("?"), except a bottle's current top unit,
     which is always visible (you need it to judge legal pours). A unit
     that's ever been the top stays revealed permanently, even if a later
     pour covers it again — see wsRevealTops().
   - Locked bottles: fully inert (can't be poured into or out of) and
     covered, showing only a dot in the color they need. They unlock the
     moment that color is fully isolated into one pure bottle *elsewhere* on
     the board (the triggering bottle isn't consumed) — see wsCheckUnlocks().

   Levels are static data (WS_LEVELS below) rather than generated live in
   the browser. Earlier attempts at live seeded-PRNG generation (simulating
   legal pours starting from a solved state, then unscrambling) kept
   producing boards with an isolated color bottle left untouched — and
   therefore still solved on load — because once the spare bottles
   saturate, a randomly-touched color has nowhere left to go, so a specific
   color could go untouched indefinitely. Real per-level data sidesteps
   this: each entry was generated offline (scripts/generate-ws-levels.js)
   by dealing a genuinely shuffled deck of color units into bottles, then
   independently verified solvable (respecting locked-bottle rules) via
   repeated randomized playouts before being accepted — see that script for
   the full generation/verification process. Only the shuffled play order,
   position in it, and the live in-progress bottle state are persisted in
   the save; the level layouts themselves ship with the app.
══════════════════════════════════════════════════════════ */

const WS_CAPACITY          = 4;
const WS_MAX_EXTRA_BOTTLES = 3;
const WS_COLORS = [
  "#e8735a", "#5aa8e8", "#6fd88a", "#e8d95a", "#b06fe8",
  "#e86fb0", "#5adfd0", "#e8a45a", "#8a9be0",
];

// Generated by scripts/generate-ws-levels.js — each entry is one level's
// starting bottle layout: b = bottles bottom→top (color indices into
// WS_COLORS, [] = empty), f = per-bottle fog bitmask (bit k set = unit
// index k starts hidden; never set for a bottle's top index or for locked
// bottles), l = locked bottles as {i: bottle index, c: required unlock
// color index}.
const WS_LEVELS = [{"b":[[4,1,0,2],[1,2,4,3],[0,2,3,4],[3,0,4,0],[2,3,1,1],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[3,1,4,0],[0,3,3,1],[2,1,4,0],[1,4,2,0],[4,2,3,2],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[3,3,0,1],[3,4,1,0],[0,2,4,2],[2,2,1,1],[4,0,3,4],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[0,4,1,2],[3,1,2,0],[2,3,0,4],[4,2,3,3],[0,1,1,4],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[4,1,2,3],[1,2,0,2],[2,4,1,0],[3,3,3,1],[4,0,4,0],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[1,2,1,2],[4,4,3,0],[3,1,0,0],[1,3,2,3],[2,0,4,4],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[4,3,4,1],[2,0,4,0],[4,0,2,3],[1,1,2,2],[3,3,1,0],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[0,3,3,1],[3,2,3,4],[4,2,1,0],[2,1,0,4],[0,1,2,4],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[3,1,3,2],[2,0,3,0],[1,0,2,1],[4,4,2,4],[4,3,1,0],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[4,0,0,0],[2,2,3,2],[1,4,1,3],[0,4,3,1],[1,4,2,3],[]],"f":[0,0,0,0,0,0],"l":[]},{"b":[[2,1,0,2],[5,4,5,3],[5,2,0,3],[0,4,4,0],[3,2,1,4],[1,5,3,1],[]],"f":[1,0,5,0,0,1,0],"l":[]},{"b":[[2,1,0,5],[3,3,4,2],[1,4,3,4],[0,3,5,2],[0,2,1,0],[5,5,1,4],[]],"f":[0,0,1,0,2,2,0],"l":[]},{"b":[[5,3,3,4],[1,2,0,5],[5,5,2,3],[3,1,0,1],[2,0,1,2],[4,4,0,4],[]],"f":[5,1,0,0,2,0,0],"l":[]},{"b":[[4,5,2,0],[5,1,4,3],[2,2,3,0],[1,2,3,0],[3,1,0,1],[5,4,5,4],[]],"f":[4,1,1,1,0,0,0],"l":[]},{"b":[[5,5,0,3],[4,1,1,4],[3,2,4,5],[2,0,0,1],[1,2,3,2],[0,3,5,4],[]],"f":[0,2,0,0,0,0,0],"l":[]},{"b":[[2,1,3,0],[0,1,5,2],[4,3,4,4],[5,0,3,0],[1,4,5,2],[3,5,2,1],[]],"f":[1,4,0,0,0,0,0],"l":[]},{"b":[[5,3,2,1],[0,2,3,0],[4,4,1,2],[0,1,5,3],[1,2,0,3],[5,5,4,4],[]],"f":[1,0,2,2,2,0,0],"l":[]},{"b":[[5,1,3,2],[4,0,0,4],[4,4,3,2],[2,5,1,3],[1,0,5,3],[0,2,1,5],[]],"f":[1,0,0,4,0,0,0],"l":[]},{"b":[[4,1,1,3],[4,2,2,3],[3,0,5,5],[5,5,1,4],[2,0,0,4],[0,3,2,1],[]],"f":[0,0,0,0,0,0,0],"l":[]},{"b":[[4,1,3,4],[0,3,5,0],[3,4,3,5],[1,0,2,5],[0,2,5,1],[2,4,1,2],[]],"f":[0,2,0,0,0,0,0],"l":[]},{"b":[[5,2,3,4],[0,1,2,4],[2,2,0,0],[5,1,1,5],[0,3,3,1],[3,5,4,4],[]],"f":[0,1,1,0,0,0,0],"l":[]},{"b":[[2,3,3,3],[5,2,2,4],[3,0,1,2],[5,5,5,4],[4,1,0,1],[0,4,0,1],[]],"f":[0,0,0,0,0,7,0],"l":[]},{"b":[[3,1,4,3],[2,5,0,4],[1,5,2,4],[5,2,2,0],[0,5,3,1],[0,3,1,4],[]],"f":[4,4,0,0,2,0,0],"l":[]},{"b":[[4,3,4,2],[5,3,0,1],[0,0,5,4],[4,1,5,2],[1,2,2,0],[3,5,3,1],[]],"f":[4,0,0,0,0,0,0],"l":[]},{"b":[[3,3,4,1],[2,0,1,3],[5,4,5,0],[1,5,0,2],[1,2,5,2],[4,3,4,0],[]],"f":[0,0,0,2,2,0,0],"l":[]},{"b":[[2,2,1,0],[5,1,4,5],[4,2,6,1],[3,0,6,5],[1,3,6,3],[2,5,3,0],[0,4,6,4],[]],"f":[0,4,4,4,1,5,0,0],"l":[]},{"b":[[6,6,1,2],[5,3,5,3],[3,0,2,1],[0,4,6,4],[4,5,2,5],[6,1,2,3],[1,4,0,0],[]],"f":[1,0,0,3,3,1,2,0],"l":[]},{"b":[[2,5,5,5],[1,3,4,2],[6,3,1,3],[4,6,0,0],[4,0,4,5],[0,2,2,1],[3,1,6,6],[]],"f":[6,2,2,0,3,6,0,0],"l":[]},{"b":[[0,3,2,3],[0,5,6,5],[6,1,5,4],[3,2,4,0],[5,1,1,6],[2,6,0,2],[4,1,3,4],[]],"f":[1,4,0,1,4,0,1,0],"l":[]},{"b":[[3,2,1,2],[0,6,4,6],[4,3,4,0],[5,5,3,5],[4,6,1,6],[2,0,0,1],[2,1,5,3],[]],"f":[3,1,0,1,1,2,1,0],"l":[]},{"b":[[3,5,2,6],[5,6,3,2],[1,3,5,2],[4,5,4,0],[6,1,1,0],[3,4,6,0],[4,1,2,0],[]],"f":[0,0,4,4,0,0,2,0],"l":[]},{"b":[[0,0,5,1],[6,3,2,3],[6,2,6,5],[4,4,0,1],[2,3,5,4],[5,6,1,0],[4,2,3,1],[]],"f":[1,7,3,6,0,2,0,0],"l":[]},{"b":[[5,4,1,2],[6,4,5,5],[4,3,1,3],[3,0,6,0],[2,5,1,4],[6,2,3,1],[6,0,0,2],[]],"f":[1,2,1,4,1,1,1,0],"l":[]},{"b":[[5,5,3,1],[4,1,3,2],[6,4,5,1],[1,2,6,3],[2,0,4,5],[0,6,6,0],[3,4,0,2],[]],"f":[2,6,2,2,5,0,5,0],"l":[]},{"b":[[0,5,3,6],[4,5,4,1],[1,2,3,5],[3,1,2,6],[3,0,0,4],[2,2,0,6],[1,4,5,6],[]],"f":[5,7,0,0,5,4,3,0],"l":[]},{"b":[[2,0,6,6],[5,5,2,1],[1,3,4,0],[3,4,3,2],[0,6,3,5],[4,2,0,1],[6,5,4,1],[]],"f":[4,0,2,0,0,0,0,0],"l":[]},{"b":[[4,3,0,1],[5,0,5,3],[6,2,2,6],[1,4,1,0],[4,6,4,2],[2,5,0,3],[3,5,6,1],[]],"f":[4,0,4,0,4,1,0,0],"l":[]},{"b":[[6,0,6,4],[3,1,5,1],[0,2,0,3],[1,5,2,2],[2,5,3,4],[6,3,6,4],[5,1,0,4],[]],"f":[0,0,2,0,0,0,5,0],"l":[]},{"b":[[4,3,4,1],[1,4,3,6],[0,0,2,0],[0,1,6,4],[3,2,3,5],[5,5,2,6],[1,2,5,6],[]],"f":[0,6,0,4,2,2,5,0],"l":[]},{"b":[[6,3,2,5],[2,4,6,4],[2,6,5,0],[0,1,4,0],[4,1,1,2],[3,5,3,3],[1,0,6,5],[]],"f":[2,4,4,4,1,1,4,0],"l":[]},{"b":[[3,4,0,4],[1,6,6,6],[5,1,1,2],[0,2,1,5],[6,5,3,4],[0,3,2,0],[2,5,4,3],[]],"f":[0,4,0,4,0,6,0,0],"l":[]},{"b":[[1,6,4,3],[6,3,1,5],[2,0,0,4],[0,3,2,1],[3,1,5,6],[5,0,4,4],[2,6,2,5],[]],"f":[5,1,4,0,4,0,0,0],"l":[]},{"b":[[6,4,3,4],[1,0,5,3],[0,0,6,0],[5,3,2,2],[3,1,4,5],[4,2,6,1],[2,5,1,6],[]],"f":[5,4,1,2,1,4,0,0],"l":[]},{"b":[[3,1,2,1],[3,0,3,6],[4,4,5,2],[0,5,0,5],[2,2,3,0],[6,4,4,6],[5,6,1,1],[]],"f":[4,2,4,3,0,2,0,0],"l":[]},{"b":[[2,0,5,3],[0,6,1,4],[5,4,1,0],[6,3,3,2],[1,4,5,6],[4,2,5,2],[3,1,6,0],[]],"f":[0,4,0,4,1,2,0,0],"l":[]},{"b":[[2,6,3,7],[3,1,7,7],[5,3,4,7],[2,3,0,5],[4,1,4,0],[6,6,2,5],[1,6,0,1],[0,5,4,2],[]],"f":[1,1,6,4,2,0,0,0,0],"l":[{"i":6,"c":7}]},{"b":[[1,6,4,4],[4,7,1,3],[5,7,0,7],[0,4,5,3],[6,6,5,3],[1,0,2,6],[2,3,1,2],[7,5,2,0],[]],"f":[2,4,0,3,6,5,1,4,0],"l":[{"i":2,"c":3}]},{"b":[[7,2,6,3],[4,3,5,1],[1,4,4,1],[7,6,0,0],[5,4,2,5],[7,2,3,0],[3,5,7,6],[2,1,6,0],[]],"f":[5,0,0,0,3,0,6,1,0],"l":[{"i":1,"c":0}]},{"b":[[2,0,0,7],[7,2,0,6],[5,7,1,1],[0,5,3,7],[3,2,3,5],[6,6,1,4],[1,4,4,4],[3,6,5,2],[]],"f":[0,4,0,1,0,4,0,0,0],"l":[{"i":4,"c":4}]},{"b":[[7,1,2,0],[1,5,3,4],[0,7,3,4],[2,2,6,1],[0,4,5,4],[5,3,7,7],[6,6,1,2],[3,0,5,6],[]],"f":[2,5,2,3,4,2,0,0,0],"l":[{"i":6,"c":4}]},{"b":[[7,6,5,3],[5,0,1,0],[4,6,2,1],[2,7,4,3],[1,5,7,3],[6,2,0,1],[0,4,6,4],[2,5,3,7],[]],"f":[0,6,1,4,4,0,5,2,0],"l":[{"i":5,"c":3}]},{"b":[[1,2,4,6],[2,3,3,0],[5,1,6,0],[4,3,2,7],[3,6,1,7],[0,1,7,7],[5,2,4,5],[6,4,5,0],[]],"f":[7,0,0,2,5,4,0,2,0],"l":[{"i":1,"c":7}]},{"b":[[6,2,4,1],[5,1,1,2],[3,5,2,7],[6,3,0,7],[4,0,3,7],[2,4,3,7],[0,4,6,5],[1,5,0,6],[]],"f":[0,0,1,0,2,4,4,4,0],"l":[{"i":1,"c":7}]},{"b":[[5,5,7,7],[4,2,3,4],[0,0,3,2],[0,6,3,5],[6,4,2,1],[1,1,7,0],[2,4,1,7],[3,5,6,6],[]],"f":[3,0,5,6,1,0,4,2,0],"l":[{"i":1,"c":1}]},{"b":[[6,3,2,5],[2,1,3,1],[6,7,0,5],[0,6,3,6],[5,5,0,7],[4,0,7,2],[1,4,1,4],[7,2,3,4],[]],"f":[0,0,4,2,5,1,4,2,0],"l":[{"i":1,"c":5}]},{"b":[[6,2,2,2],[2,3,7,4],[3,6,7,4],[7,7,5,1],[1,3,6,0],[5,5,0,4],[0,0,4,1],[5,1,6,3],[]],"f":[0,2,0,0,4,7,5,1,0],"l":[{"i":3,"c":0}]},{"b":[[2,3,1,1],[3,6,2,4],[1,1,7,4],[6,5,0,2],[6,3,4,7],[0,7,0,0],[4,7,5,5],[5,2,6,3],[]],"f":[0,4,5,0,4,0,2,1,0],"l":[{"i":0,"c":0}]},{"b":[[5,4,6,7],[6,5,0,2],[7,0,1,2],[1,1,0,7],[6,0,4,3],[3,7,2,2],[4,3,3,5],[5,4,6,1],[]],"f":[0,2,4,4,1,2,0,1,0],"l":[{"i":6,"c":2}]},{"b":[[4,5,5,7],[3,3,3,6],[0,2,4,1],[2,4,1,2],[0,6,6,1],[3,7,2,7],[6,7,1,4],[5,5,0,0],[]],"f":[0,6,0,4,0,4,2,0,0],"l":[{"i":0,"c":1}]},{"b":[[7,6,2,3],[1,4,3,4],[5,0,6,2],[2,2,7,1],[0,0,0,1],[7,4,5,3],[4,7,1,6],[6,5,3,5],[]],"f":[2,0,7,0,0,4,3,1,0],"l":[{"i":4,"c":3}]},{"b":[[4,2,3,5],[1,8,5,4],[8,0,6,2],[2,1,1,4],[7,4,1,3],[0,6,5,0],[6,3,2,6],[7,8,8,5],[3,0,7,7],[]],"f":[5,5,2,6,1,2,0,4,6,0],"l":[{"i":6,"c":1}]},{"b":[[1,2,1,2],[0,8,0,5],[4,4,3,5],[8,1,2,6],[7,1,4,6],[7,8,0,4],[3,0,7,3],[2,6,5,7],[6,3,5,8],[]],"f":[0,0,4,2,4,6,1,0,2,0],"l":[{"i":0,"c":5}]},{"b":[[8,5,5,3],[1,6,0,2],[1,4,2,7],[7,1,7,2],[4,0,4,2],[0,8,3,1],[3,7,0,6],[8,6,8,5],[5,4,6,3],[]],"f":[1,5,1,5,3,0,0,1,0,0],"l":[{"i":8,"c":2}]},{"b":[[6,1,1,1],[4,5,2,2],[3,8,7,0],[1,8,6,2],[7,6,0,3],[5,6,3,4],[3,7,4,8],[8,4,2,5],[0,0,5,7],[]],"f":[0,6,7,2,1,0,4,0,0,0],"l":[{"i":5,"c":2}]},{"b":[[3,7,5,4],[0,1,3,7],[7,8,3,2],[8,6,0,6],[5,8,6,8],[0,4,1,2],[1,5,1,0],[4,3,7,2],[6,2,5,4],[]],"f":[1,5,0,0,0,5,0,5,4,0],"l":[{"i":6,"c":2}]},{"b":[[8,0,7,0],[4,6,2,8],[2,6,3,3],[2,5,1,6],[0,5,4,7],[5,7,5,3],[1,4,0,4],[7,1,8,1],[2,8,6,3],[]],"f":[2,1,0,1,0,3,5,4,5,0],"l":[{"i":4,"c":3}]},{"b":[[6,8,1,3],[1,8,4,2],[5,7,3,4],[6,0,6,3],[3,1,4,8],[8,5,2,0],[7,5,0,7],[2,2,5,6],[0,4,7,1],[]],"f":[2,1,0,0,0,4,7,1,1,0],"l":[{"i":3,"c":4}]},{"b":[[5,4,0,2],[3,6,4,7],[7,0,5,1],[8,0,7,4],[4,2,8,1],[3,2,3,1],[2,5,0,3],[6,8,6,5],[1,7,6,8],[]],"f":[0,4,4,2,5,0,3,7,5,0],"l":[{"i":0,"c":1}]},{"b":[[6,3,2,1],[8,7,7,3],[0,6,0,7],[1,5,0,8],[5,4,4,6],[0,8,8,4],[4,3,6,7],[2,1,1,2],[3,2,5,5],[]],"f":[0,0,6,4,0,5,3,0,2,0],"l":[{"i":0,"c":8}]},{"b":[[1,2,8,1],[5,7,3,4],[8,1,3,6],[3,6,7,0],[7,3,1,0],[2,5,4,7],[4,0,0,2],[5,5,8,4],[6,8,6,2],[]],"f":[1,3,3,3,4,2,2,5,0,0],"l":[{"i":8,"c":4}]},{"b":[[4,0,4,3],[6,5,6,5],[2,4,2,1],[0,2,1,6],[4,6,5,5],[3,1,3,1],[3,0,2,0],[]],"f":[0,2,4,1,0,0,5,0],"l":[{"i":0,"c":6},{"i":5,"c":5}]},{"b":[[4,3,5,2],[2,6,5,4],[6,2,1,1],[5,1,2,6],[1,0,3,3],[4,5,4,6],[0,0,3,0],[]],"f":[2,0,5,0,0,1,0,0],"l":[{"i":6,"c":2},{"i":4,"c":6}]},{"b":[[3,5,2,4],[5,3,3,4],[6,3,5,6],[2,5,6,0],[4,4,2,1],[6,2,1,0],[1,1,0,0],[]],"f":[0,3,0,2,1,5,3,0],"l":[{"i":2,"c":0},{"i":0,"c":1}]},{"b":[[1,3,4,0],[0,1,5,3],[4,6,6,6],[3,5,2,2],[5,5,1,2],[4,2,3,1],[0,0,4,6],[]],"f":[0,0,6,1,2,5,1,0],"l":[{"i":0,"c":2},{"i":1,"c":6}]},{"b":[[0,6,2,5],[5,6,5,2],[4,1,1,3],[1,5,4,2],[0,3,0,4],[3,1,6,4],[6,0,3,2],[]],"f":[0,0,0,5,0,0,2,0],"l":[{"i":5,"c":2},{"i":4,"c":5}]},{"b":[[3,1,3,1],[5,3,1,3],[4,0,2,1],[6,0,4,2],[2,4,6,5],[0,6,6,5],[2,5,0,4],[]],"f":[2,5,4,0,3,0,4,0],"l":[{"i":5,"c":1},{"i":3,"c":3}]},{"b":[[1,1,3,4],[0,5,1,4],[3,0,5,5],[2,2,6,6],[6,2,2,4],[5,3,4,0],[6,0,1,3],[]],"f":[2,1,0,0,2,0,4,0],"l":[{"i":3,"c":1},{"i":2,"c":4}]},{"b":[[3,5,1,5],[6,0,4,4],[5,4,0,0],[0,2,3,6],[3,1,1,2],[1,2,2,4],[3,6,6,5],[]],"f":[7,0,0,0,0,6,7,0],"l":[{"i":3,"c":5},{"i":4,"c":4}]},{"b":[[6,3,3,2],[3,5,0,1],[6,6,4,4],[5,3,5,1],[4,1,2,0],[0,0,2,2],[5,4,6,1],[]],"f":[5,3,4,0,6,4,0,0],"l":[{"i":6,"c":0},{"i":3,"c":2}]},{"b":[[4,5,1,6],[1,4,4,2],[3,6,2,2],[5,5,5,3],[0,1,3,0],[3,6,0,2],[0,6,4,1],[]],"f":[2,3,5,0,0,2,0,0],"l":[{"i":4,"c":2},{"i":3,"c":6}]}];
const WS_LEVEL_COUNT = WS_LEVELS.length;

function wsGenerateLevel(levelIndex) {
  const level = WS_LEVELS[levelIndex];
  const lockOf = new Map((level.l || []).map(e => [e.i, e.c]));
  return level.b.map((colorIdxs, i) => {
    const isLocked = lockOf.has(i);
    const fogMask = (level.f && level.f[i]) || 0;
    const units = colorIdxs.map((ci, u) => ({
      c: WS_COLORS[ci],
      h: !isLocked && !!(fogMask & (1 << u)),
    }));
    if (!isLocked && units.length) units[units.length - 1].h = false; // defensive: top always visible
    return { units, locked: isLocked, unlockColor: isLocked ? WS_COLORS[lockOf.get(i)] : null };
  });
}

/* ── core pour rules — operate on bottle objects {units, locked, unlockColor} ── */
function wsTopRun(bottle) {
  const units = bottle.units;
  if (!units.length) return { color: null, len: 0 };
  const color = units[units.length - 1].c;
  let len = 1;
  while (len < units.length && units[units.length - 1 - len].c === color) len++;
  return { color, len };
}
function wsCanPour(bottles, from, to) {
  if (from === to) return false;
  const src = bottles[from], dst = bottles[to];
  if (!src || !dst || src.locked || dst.locked) return false;
  if (!src.units.length || dst.units.length >= WS_CAPACITY) return false;
  const top = src.units[src.units.length - 1].c;
  return dst.units.length === 0 || dst.units[dst.units.length - 1].c === top;
}
function wsPour(bottles, from, to) {
  if (!wsCanPour(bottles, from, to)) return 0;
  const { len } = wsTopRun(bottles[from]);
  const amt = Math.min(len, WS_CAPACITY - bottles[to].units.length);
  for (let i = 0; i < amt; i++) bottles[to].units.push(bottles[from].units.pop());
  return amt;
}
function wsIsSolved(bottles) {
  return bottles.every(b => {
    if (b.locked) return false;
    return b.units.length === 0 ||
      (b.units.length === WS_CAPACITY && b.units.every(u => u.c === b.units[0].c));
  });
}

// "Top is always visible" invariant restorer — call after any mutation
// (pour, extra bottle added, level start, unlock) so a covered-then-
// re-exposed unit is never silently hidden again.
function wsRevealTops(bottles) {
  for (const b of bottles) {
    if (b.locked || !b.units.length) continue;
    const top = b.units[b.units.length - 1];
    if (top.h) top.h = false;
  }
}

// Unlocks a locked bottle the moment some OTHER, non-locked bottle is full
// and monochrome in that lock's required color. The triggering bottle is
// left untouched — it stays a normal completed bottle, the locked one just
// becomes a second, independent, now-interactive bottle.
function wsCheckUnlocks(bottles) {
  let changed = false;
  for (const b of bottles) {
    if (!b.locked) continue;
    const available = bottles.some(o =>
      o !== b && !o.locked && o.units.length === WS_CAPACITY &&
      o.units.every(u => u.c === b.unlockColor));
    if (available) { b.locked = false; changed = true; }
  }
  if (changed) wsRevealTops(bottles);
  return changed;
}

// "Bottle done" = would count as solved on its own (empty, or full +
// monochrome) — mirrors the per-bottle check already inline in wsIsSolved.
function wsBottleIsDone(bottle) {
  if (bottle.locked) return false;
  return bottle.units.length === 0 ||
    (bottle.units.length === WS_CAPACITY && bottle.units.every(u => u.c === bottle.units[0].c));
}

/* ══════════════════════════════════════════════════════════
   GAME FLOW — reads/writes G.waterSort
══════════════════════════════════════════════════════════ */
// Transient, purely-visual hints for wsRender() — never persisted in G,
// since they're meaningless (and would just be stale) after a reload.
let wsLastPourAnim = null;       // { from, to, amt } | null
let wsCelebratedBottles = new Set(); // bottle indices that already played their one-shot done-pulse this level

function wsOnBottleTap(idx) {
  const ws = G.waterSort;
  const bottle = ws.bottles[idx];
  if (!bottle || bottle.locked) return; // locked bottles are fully inert
  if (ws.selectedBottle === null) {
    if (bottle.units.length) { ws.selectedBottle = idx; wsRender(); }
    return;
  }
  if (ws.selectedBottle === idx) { ws.selectedBottle = null; wsRender(); return; }
  const fromIdx = ws.selectedBottle;
  const amt = wsPour(ws.bottles, fromIdx, idx);
  ws.selectedBottle = null;
  if (amt > 0) {
    wsLastPourAnim = { from: fromIdx, to: idx, amt };
    wsRevealTops(ws.bottles);
    wsCheckUnlocks(ws.bottles);
    saveState(); // explicit — mid-level progress must survive a reload
    if (wsIsSolved(ws.bottles)) { wsOnLevelSolved(); return; }
  }
  wsRender();
}
window.wsOnBottleTap = wsOnBottleTap;

function wsOnLevelSolved() {
  G.stats.waterSortLevelsCompleted = (G.stats.waterSortLevelsCompleted || 0) + 1;
  checkTrophies();
  showToast("🧪 Level gelöst!");
  saveState();
  wsRender();
  setTimeout(wsAdvanceToNextLevel, 900);
}

function wsAdvanceToNextLevel() {
  const ws = G.waterSort;
  ws.playOrderPos++;
  if (ws.playOrderPos >= ws.playOrder.length) {
    const prevLast = ws.playOrder[ws.playOrder.length - 1];
    const order = shuffleArray([...Array(WS_LEVEL_COUNT).keys()]);
    if (order[0] === prevLast) [order[0], order[1]] = [order[1], order[0]];
    ws.playOrder = order;
    ws.playOrderPos = 0;
  }
  wsStartLevel(ws.playOrder[ws.playOrderPos]);
}

function wsStartLevel(levelIndex) {
  const ws = G.waterSort;
  ws.currentLevelIndex = levelIndex;
  ws.bottles = wsGenerateLevel(levelIndex);
  wsRevealTops(ws.bottles);
  ws.extraBottlesUsed = 0;
  ws.selectedBottle = null;
  wsLastPourAnim = null;
  wsCelebratedBottles = new Set();
  saveState();
  wsRender();
}

function wsRestartLevel() {
  const ws = G.waterSort;
  if (ws.currentLevelIndex == null) return;
  wsStartLevel(ws.currentLevelIndex);
  showToast("🔄 Level neu gestartet.");
}
window.wsRestartLevel = wsRestartLevel;

function wsEnsureQueueAndLevel() {
  const ws = G.waterSort;
  if (!ws.playOrder.length) {
    ws.playOrder = shuffleArray([...Array(WS_LEVEL_COUNT).keys()]);
    ws.playOrderPos = 0;
  }
  if (ws.currentLevelIndex == null || !ws.bottles.length) {
    wsStartLevel(ws.playOrder[ws.playOrderPos]);
  } else {
    wsRender();
  }
}
window.wsEnsureQueueAndLevel = wsEnsureQueueAndLevel;

function wsBuyExtraBottle() {
  const ws = G.waterSort;
  if (ws.extraBottlesUsed >= WS_MAX_EXTRA_BOTTLES) {
    showToast(`Maximal ${WS_MAX_EXTRA_BOTTLES} Extra-Fläschchen pro Level!`);
    return;
  }
  if (!hasActiveQuestions()) {
    showToast("Keine aktiven Fragen! Aktiviere Kapitel unter 📚.");
    return;
  }
  askQuestions("🧪 Extra-Fläschchen", 1, () => {
    ws.bottles.push({ units: [], locked: false, unlockColor: null });
    wsRevealTops(ws.bottles);
    ws.extraBottlesUsed++;
    G.stats.waterSortExtraBottlesBought = (G.stats.waterSortExtraBottlesBought || 0) + 1;
    checkTrophies();
    saveState();
    wsRender();
    showToast("🧪 Neues Fläschchen erhalten!");
  }, null);
}
window.wsBuyExtraBottle = wsBuyExtraBottle;

/* ══════════════════════════════════════════════════════════
   RENDERING
══════════════════════════════════════════════════════════ */
function wsRender() {
  const ws = G.waterSort;
  const infoEl = document.getElementById("ws-level-info");
  const gridEl = document.getElementById("ws-bottle-grid");
  const buyBtn = document.getElementById("ws-buy-bottle-btn");
  if (!gridEl) return;

  if (infoEl) {
    infoEl.textContent = ws.currentLevelIndex == null
      ? ""
      : `Level ${ws.currentLevelIndex + 1} / ${WS_LEVEL_COUNT}`;
  }

  const pourAnim = wsLastPourAnim;
  wsLastPourAnim = null; // consume — a later, unrelated render must not replay it

  gridEl.innerHTML = (ws.bottles || []).map((bottle, idx) => {
    if (bottle.locked) {
      return `<div class="ws-bottle ws-bottle--locked" data-idx="${idx}">
        <div class="ws-bottle-stack ws-bottle-stack--locked">
          <div class="ws-lock-cover"><div class="ws-lock-dot" style="background:${bottle.unlockColor}"></div></div>
        </div>
      </div>`;
    }
    const incomingFrom = pourAnim && pourAnim.to === idx ? bottle.units.length - pourAnim.amt : Infinity;
    const slots = [];
    for (let i = 0; i < WS_CAPACITY; i++) {
      const unit = bottle.units[i];
      if (!unit) { slots.push(`<div class="ws-segment ws-segment--empty"></div>`); continue; }
      const incoming = i >= incomingFrom;
      const incomingCls = incoming ? ' ws-segment--incoming' : '';
      const delayStyle = incoming ? `animation-delay:${(i - incomingFrom) * 60}ms;` : '';
      if (unit.h) slots.push(`<div class="ws-segment ws-segment--fog${incomingCls}" style="${delayStyle}"></div>`);
      else slots.push(`<div class="ws-segment${incomingCls}" style="background:${unit.c};${delayStyle}"></div>`);
    }
    let cls = "ws-bottle";
    if (ws.selectedBottle === idx) cls += " ws-bottle--selected";
    if (pourAnim && pourAnim.from === idx) cls += " ws-bottle--pouring";
    const done = wsBottleIsDone(bottle);
    if (done) {
      cls += " ws-bottle--complete";
      if (!wsCelebratedBottles.has(idx)) {
        cls += " ws-bottle--complete-pulse";
        wsCelebratedBottles.add(idx);
      }
    }
    return `<div class="${cls}" data-idx="${idx}">
      <div class="ws-bottle-stack">${slots.join("")}</div>
    </div>`;
  }).join("");

  gridEl.querySelectorAll(".ws-bottle").forEach(el => {
    el.onclick = () => wsOnBottleTap(parseInt(el.dataset.idx, 10));
  });

  if (buyBtn) {
    const atCap = (ws.extraBottlesUsed || 0) >= WS_MAX_EXTRA_BOTTLES;
    buyBtn.disabled = atCap;
    buyBtn.classList.toggle("ws-buy-bottle-btn--off", atCap);
    buyBtn.textContent = atCap
      ? "➕ Maximal erreicht"
      : `➕ Extra-Fläschchen (1 Frage) · ${ws.extraBottlesUsed || 0}/${WS_MAX_EXTRA_BOTTLES}`;
  }
}
window.wsRender = wsRender;
